-- 添加词汇 201-300
INSERT INTO words (word_id, word, phonetic, pos, definition, family, examples, roots) VALUES
('w_0201','extract','/ˈekstrækt/','verb','v. 提取','[]','["Extract information."]','["ex","tract"]'),
('w_0202','protract','/prəˈtrækt/','verb','v. 延长','[]','["Protract the meeting."]','["pro","tract"]'),
('w_0203','converse','/kənˈvɜːs/','verb','v. 交谈','[]','["Converse in English."]','["con","verse"]'),
('w_0204','reverse','/rɪˈvɜːs/','verb','v. 颠倒','[]','["Reverse the order."]','["re","verse"]'),
('w_0205','adverse','/ˈædvɜːs/','adj','adj. 不利的','[]','["Adverse conditions."]','["ad","verse"]'),
('w_0206','diverse','/daɪˈvɜːs/','adj','adj. 多样的','[]','["Diverse opinions."]','["di","verse"]'),
('w_0207','universe','/ˈjuːnɪvɜːs/','noun','n. 宇宙','[]','["The universe."]','["uni","verse"]'),
('w_0208','anniversary','/ˌænɪˈvɜːsəri/','noun','n. 周年纪念','[]','["Wedding anniversary."]','["annus","verse"]'),
('w_0209','compose','/kəmˈpəʊz/','verb','v. 组成','[]','["Compose music."]','["com","pose"]'),
('w_0210','decompose','/ˌdiːkəmˈpəʊz/','verb','v. 分解','[]','["Decompose matter."]','["de","com","pose"]'),
('w_0211','dispose','/dɪˈspəʊz/','verb','v. 处理','[]','["Dispose of waste."]','["dis","pose"]'),
('w_0212','expose','/ɪkˈspəʊz/','verb','v. 暴露','[]','["Expose to light."]','["ex","pose"]'),
('w_0213','impose','/ɪmˈpəʊz/','verb','v. 强制推行','[]','["Impose rules."]','["im","pose"]'),
('w_0214','oppose','/əˈpəʊz/','verb','v. 反对','[]','["Oppose the plan."]','["op","pose"]'),
('w_0215','propose','/prəˈpəʊz/','verb','v. 提议','[]','["Propose a solution."]','["pro","pose"]'),
('w_0216','suppose','/səˈpəʊz/','verb','v. 假设','[]','["I suppose so."]','["sup","pose"]'),
('w_0217','structure','/ˈstrʌktʃər/','noun','n. 结构','["structural"]','["Social structure."]','["struct"]'),
('w_0218','construct','/kənˈstrʌkt/','verb','v. 建造','[]','["Construct a building."]','["con","struct"]'),
('w_0219','destruction','/dɪˈstrʌkʃən/','noun','n. 破坏','[]','["Environmental destruction."]','["de","struct"]'),
('w_0220','instruct','/ɪnˈstrʌkt/','verb','v. 指导','[]','["Instruct students."]','["in","struct"]'),
('w_0221','obstruct','/əbˈstrʌkt/','verb','v. 阻碍','[]','["Obstruct the view."]','["ob","struct"]'),
('w_0222','instrument','/ˈɪnstrʊmənt/','noun','n. 仪器','[]','["Musical instrument."]','["in","stru"]'),
('w_0223','comprehend','/ˌkɒmprɪˈhend/','verb','v. 理解','[]','["Comprehend the text."]','["com","prehend"]'),
('w_0224','apprehend','/ˌæprɪˈhend/','verb','v. 理解，逮捕','[]','["Apprehend the criminal."]','["ap","prehend"]'),
('w_0225','repress','/rɪˈpres/','verb','v. 抑制','[]','["Repress emotions."]','["re","press"]'),
('w_0226','suppress','/səˈpres/','verb','v. 压制','[]','["Suppress the news."]','["sup","press"]'),
('w_0227','compress','/kəmˈpres/','verb','v. 压缩','[]','["Compress the file."]','["com","press"]'),
('w_0228','depress','/dɪˈpres/','verb','v. 使沮丧','[]','["Depress the economy."]','["de","press"]'),
('w_0229','impress','/ɪmˈpres/','verb','v. 留下印象','[]','["Impress the interviewer."]','["im","press"]'),
('w_0230','express','/ɪkˈspres/','verb','v. 表达','[]','["Express your feelings."]','["ex","press"]'),
('w_0231','aggressive','/əˈɡresɪv/','adj','adj. 侵略性的','[]','["Aggressive behavior."]','["ag","gress"]'),
('w_0232','congress','/ˈkɒŋɡres/','noun','n. 国会','[]','["US Congress."]','["con","gress"]'),
('w_0233','progress','/ˈprɒɡres/','noun','n. 进步','[]','["Make progress."]','["pro","gress"]'),
('w_0234','regress','/rɪˈɡres/','verb','v. 退步','[]','[" regress to old habits."]','["re","gress"]'),
('w_0235','transgress','/trænzˈɡres/','verb','v. 违反','[]','["Transgress the law."]','["trans","gress"]'),
('w_0236','graduate','/ˈɡrædʒʊət/','noun','n. 毕业生','[]','["College graduate."]','["grad"]'),
('w_0237','undergraduate','/ˌʌndəˈɡrædʒʊət/','noun','n. 大学生','[]','["Undergraduate student."]','["under","grad"]'),
('w_0238','degrade','/dɪˈɡreɪd/','verb','v. 贬低','[]','["Degrade quality."]','["de","grade"]'),
('w_0239','upgrade','/ʌpˈɡreɪd/','verb','v. 升级','[]','["Upgrade software."]','["up","grade"]'),
('w_0240','ingredient','/ɪnˈɡriːdɪənt/','noun','n. 成分','[]','["Food ingredients."]','["in","gred"]'),
('w_0241','agriculture','/ˈæɡrɪkʌltʃər/','noun','n. 农业','[]','["Modern agriculture."]','["agri","cult"]'),
('w_0242','cultivate','/ˈkʌltɪveɪt/','verb','v. 培养','[]','["Cultivate skills."]','["cult"]'),
('w_0243','colony','/ˈkɒləni/','noun','n. 殖民地','["colonial"]','["Former colony."]','["colony"]'),
('w_0244','colonial','/kəˈləʊniəl/','adj','adj. 殖民的','[]','["Colonial history."]','["colony"]'),
('w_0245','agriculture','/ˈæɡrɪkʌltʃər/','noun','n. 农业','[]','["Sustainable agriculture."]','["agri"]'),
('w_0246','migrate','/maɪˈɡreɪt/','verb','v. 迁移','[]','["Birds migrate south."]','["migr"]'),
('w_0247','immigrate','/ˈɪmɪɡreɪt/','verb','v. 移入','[]','["Immigrate to America."]','["im","migr"]'),
('w_0248','emigrate','/ˈemɪɡreɪt/','verb','v. 移出','[]','["Emigrate from China."]','["e","migr"]'),
('w_0249','transplant','/trænsˈplɑːnt/','verb','v. 移植','[]','["Transplant organs."]','["trans","plant"]'),
('w_0250','plant','/plɑːnt/','noun','n. 植物','[]','["Green plants."]','["plant"]'),
('w_0251','plantation','/plænˈteɪʃən/','noun','n. 种植园','[]','["Coffee plantation."]','["plant"]'),
('w_0252','supplement','/ˈsʌplɪmənt/','verb','v. 补充','[]','["Supplement diet."]','["sup","ple"]'),
('w_0253','implement','/ˈɪmplɪmənt/','verb','v. 实施','[]','["Implement policy."]','["im","ple"]'),
('w_0254','complement','/ˈkɒmplɪmənt/','verb','v. 补足','[]','["Complement each other."]','["com","ple"]'),
('w_0255','compliment','/ˈkɒmplɪmənt/','verb','v. 称赞','[]','["Compliment her dress."]','["com","pli"]'),
('w_0256','accomplish','/əˈkʌmplɪʃ/','verb','v. 完成','[]','["Accomplish goals."]','["ac","compl"]'),
('w_0257','complete','/kəmˈpliːt/','adj','adj. 完整的','[]','["Complete information."]','["com","ple"]'),
('w_0258','supply','/səˈplaɪ/','verb','v. 供应','[]','["Supply food."]','["sup","ply"]'),
('w_0259','reply','/rɪˈplaɪ/','verb','v. 回复','[]','["Reply to email."]','["re","ply"]'),
('w_0260','apply','/əˈplaɪ/','verb','v. 申请','[]','["Apply for job."]','["ap","ply"]'),
('w_0261','comply','/kəmˈplaɪ/','verb','v. 遵守','[]','["Comply with rules."]','["com","ply"]'),
('w_0262','imply','/ɪmˈplaɪ/','verb','v. 暗示','[]','["What do you imply?"]','["im","ply"]'),
('w_0263','multiply','/ˈmʌltɪplaɪ/','verb','v. 乘以','[]','["Multiply numbers."]','["multi","ply"]'),
('w_0264','employ','/ɪmˈplɔɪ/','verb','v. 雇佣','[]','["Employ workers."]','["em","ploy"]'),
('w_0265','unemployed','/ˌʌnɪmˈplɔɪd/','adj','adj. 失业的','[]','["Unemployed workers."]','["un","em","ploy"]'),
('w_0266','deploy','/dɪˈplɔɪ/','verb','v. 部署','[]','["Deploy troops."]','["de","ploy"]'),
('w_0267','display','/dɪˈspleɪ/','verb','v. 展示','[]','["Display products."]','["dis","play"]'),
('w_0268','portray','/pɔːˈtreɪ/','verb','v. 描绘','[]','["Portray characters."]','["port","tray"]'),
('w_0269','portrait','/ˈpɔːtreɪt/','noun','n. 肖像','[]','["Family portrait."]','["port","trait"]'),
('w_0270','contribute','/kənˈtrɪbjʊt/','verb','v. 贡献','[]','["Contribute to charity."]','["con","tribute"]'),
('w_0271','distribute','/dɪˈstrɪbjʊt/','verb','v. 分发','[]','["Distribute flyers."]','["dis","tribute"]'),
('w_0272','tribute','/ˈtrɪbjuːt/','noun','n. 贡品','[]','["Pay tribute."]','["tribute"]'),
('w_0273','attribute','/ˈætrɪbjuːt/','verb','v. 归因于','[]','["Attribute success to effort."]','["at","tribute"]'),
('w_0274','contribute','/kənˈtrɪbjʊt/','verb','v. 捐献','[]','["Contribute money."]','["con"]'),
('w_0275','occupy','/ˈɒkjʊpaɪ/','verb','v. 占领','[]','["Occupy the building."]','["oc","cupy"]'),
('w_0276','occupation','/ˌɒkjʊˈpeɪʃən/','noun','n. 职业','[]','["Your occupation?"]','["oc","cup"]'),
('w_0277','preoccupy','/prɪˈɒkjʊpaɪ/','verb','v. 使全神贯注','[]','["Preoccupied with work."]','["pre","oc","cupy"]'),
('w_0278','capacity','/kəˈpæsɪti/','noun','n. 容量','[]','["Production capacity."]','["cap"]'),
('w_0279','capture','/ˈkæptʃər/','verb','v. 捕获','[]','["Capture the moment."]','["cap"]'),
('w_0280','escape','/ɪˈskeɪp/','verb','v. 逃跑','[]','["Escape from prison."]','["es","cap"]'),
('w_0281','susceptible','/səˈseptɪbl/','adj','adj. 易受影响的','[]','["Susceptible to disease."]','["sus","cept"]'),
('w_0282','accept','/əkˈsept/','verb','v. 接受','[]','["Accept the offer."]','["ac","cept"]'),
('w_0283','concept','/ˈkɒnsept/','noun','n. 概念','[]','["Basic concepts."]','["con","cept"]'),
('w_0284','except','/ɪkˈsept/','prep','prep. 除了','[]','["Everyone except me."]','["ex","cept"]'),
('w_0285','receive','/rɪˈsiːv/','verb','v. 收到','[]','["Receive a letter."]','["re","ceiv"]'),
('w_0286','perceive','/pəˈsiːv/','verb','v. 感知','[]','["Perceive danger."]','["per","ceiv"]'),
('w_0287','deceive','/dɪˈsiːv/','verb','v. 欺骗','[]','["Deceive customers."]','["de","ceiv"]'),
('w_0288','conceive','/kənˈsiːv/','verb','v. 构想','[]','["Conceive a plan."]','["con","ceiv"]'),
('w_0289','achieve','/əˈtʃiːv/','verb','v. 实现','[]','["Achieve goals."]','["achiev"]'),
('w_0290','retrieve','/rɪˈtriːv/','verb','v. 检索','[]','["Retrieve data."]','["re","triev"]'),
('w_0291','believe','/bɪˈliːv/','verb','v. 相信','[]','["I believe you."]','["believ"]'),
('w_0292','relieve','/rɪˈliːv/','verb','v. 减轻','[]','["Relieve pain."]','["re","liev"]'),
('w_0293','review','/rɪˈvjuː/','verb','v. 复习','[]','["Review lessons."]','["re","view"]'),
('w_0294','preview','/ˈpriːvjuː/','verb','v. 预览','[]','["Preview movies."]','["pre","view"]'),
('w_0295','interview','/ˈɪntəvjuː/','noun','n. 面试','[]','["Job interview."]','["inter","view"]'),
('w_0296','revise','/rɪˈvaɪz/','verb','v. 修订','[]','["Revise documents."]','["re","vis"]'),
('w_0297','supervise','/ˈsuːpəvaɪz/','verb','v. 监督','[]','["Supervise workers."]','["super","vis"]'),
('w_0298','advise','/ədˈvaɪz/','verb','v. 建议','[]','["Advise patience."]','["ad","vis"]'),
('w_0299','visible','/ˈvɪzɪbl/','adj','adj. 可见的','[]','["Visible stars."]','["vis"]'),
('w_0300','vision','/ˈvɪʒən/','noun','n. 视力','[]','["Poor vision."]','["vis"]');
