-- 添加词汇 1101-1200
INSERT INTO words (word_id, word, phonetic, pos, definition, family, examples, roots) VALUES
('w_1101','activity','/ækˈtɪvɪti/','noun','n. 活动','["act"]','["Outdoor activities."]','["act"]'),
('w_1102','interact','/ˌɪntəˈækt/','verb','v. 互动','["inter","act"]','["Interact with friends."]','["inter","act"]'),
('w_1103','react','/riˈækt/','verb','v. 反应','["re","act"]','["React quickly."]','["re","act"]'),
('w_1104','exact','/ɪɡˈzækt/','adj','adj. 精确的','["ex","act"]','["Exact time."]','["ex","act"]'),
('w_1105','enact','/ɪˈnækt/','verb','v. 制定','["e","nact"]','["Enact laws."]','["e","nact"]'),
('w_1106','practice','/ˈpræktɪs/','noun','n. 练习','["pract"]','["Practice makes perfect."]','["pract"]'),
('w_1107','practical','/ˈpræktɪkəl/','adj','adj. 实际的','["pract"]','["Practical solution."]','["pract"]'),
('w_1108','practitioner','/prækˈtɪʃənər/','noun','n. 从业者','["pract"]','["Medical practitioner."]','["pract"]'),
('w_1109','alliance','/əˈlaɪəns/','noun','n. 联盟','["al","li"]','["Strategic alliance."]','["al","li"]'),
('w_1110','allied','/ˈælaɪd/','adj','adj. 联合的','["al","ly"]','["Allied forces."]','["al","ly"]'),
('w_1111','ally','/ˈælaɪ/','noun','n. 同盟国','["al","ly"]','["NATO allies."]','["al","ly"]'),
('w_1112','allocate','/ˈæləkeɪt/','verb','v. 分配','["al","loc"]','["Allocate resources."]','["al","loc"]'),
('w_1113','allow','/əˈlaʊ/','verb','v. 允许','["al","low"]','["Allow entry."]','["al","low"]'),
('w_1114','alloy','/ˈælɔɪ/','noun','n. 合金','["al","loy"]','["Steel alloy."]','["al","loy"]'),
('w_1115','alleviate','/əˈliːvɪeɪt/','verb','v. 减轻','["al","lev"]','["Alleviate pain."]','["al","lev"]'),
('w_1116','allure','/əˈljʊər/','noun','n. 吸引力','["al","lure"]','["The allure of travel."]','["al","lure"]'),
('w_1117','allude','/əˈljuːd/','verb','v. 暗指','["al","lude"]','["Allude to something."]','["al","lude"]'),
('w_1118','collude','/kəˈljuːd/','verb','v. 勾结','["col","lude"]','["Collude with rivals."]','["col","lude"]'),
('w_1119','elude','/ɪˈljuːd/','verb','v. 逃避','["e","lude"]','["Elude capture."]','["e","lude"]'),
('w_1120','delude','/dɪˈljuːd/','verb','v. 欺骗','["de","lude"]','["Delude yourself."]','["de","lude"]'),
('w_1121','ambition','/æmˈbɪʃən/','noun','n. 雄心','["amb","it"]','["Career ambition."]','["amb","it"]'),
('w_1122','ambient','/ˈæmbiənt/','adj','adj. 周围的','["amb","ient"]','["Ambient temperature."]','["amb","ient"]'),
('w_1123','ambiguous','/æmˈbɪɡjʊəs/','adj','adj. 模糊的','["amb","ig"]','["Ambiguous statement."]','["amb","ig"]'),
('w_1124','ambivalent','/æmˈbɪvələnt/','adj','adj. 矛盾的','["amb","val"]','["Ambivalent feelings."]','["amb","val"]'),
('w_1125','circumstance','/ˈsɜːkəmstəns/','noun','n. 情况','["circum","st"]','["Under circumstances."]','["circum","st"]'),
('w_1126','constant','/ˈkɒnstənt/','adj','adj. 恒定的','["con","st"]','["Constant speed."]','["con","st"]'),
('w_1127','distant','/ˈdɪstənt/','adj','adj. 遥远的','["dis","st"]','["Distant relative."]','["dis","st"]'),
('w_1128','instant','/ˈɪnstənt/','adj','adj. 立即的','["in","st"]','["Instant noodles."]','["in","st"]'),
('w_1129','substance','/ˈsʌbstəns/','noun','n. 物质','["sub","st"]','["Chemical substance."]','["sub","st"]'),
('w_1130','substantial','/səbˈstænʃəl/','adj','adj. 大量的','["sub","st"]','["Substantial progress."]','["sub","st"]'),
('w_1131','obstacle','/ˈɒbstəkl/','noun','n. 障碍','["ob","st"]','["Obstacle to success."]','["ob","st"]'),
('w_1132','stable','/ˈsteɪbl/','adj','adj. 稳定的','["st"]','["Stable economy."]','["st"]'),
('w_1133','stability','/stəˈbɪlɪti/','noun','n. 稳定性','["st"]','["Political stability."]','["st"]'),
('w_1134','stabilize','/ˈsteɪbɪlaɪz/','verb','v. 使稳定','["st"]','["Stabilize prices."]','["st"]'),
('w_1135','estate','/ɪˈsteɪt/','noun','n. 房产','["e","st"]','["Real estate."]','["e","st"]'),
('w_1136','status','/ˈsteɪtəs/','noun','n. 地位','["st"]','["Social status."]','["st"]'),
('w_1137','statute','/ˈstætʃuːt/','noun','n. 法规','["st"]','["Statute of limitations."]','["st"]'),
('w_1138','state','/steɪt/','noun','n. 州','["st"]','["State government."]','["st"]'),
('w_1139','statement','/ˈsteɪtmənt/','noun','n. 声明','["st"]','["Official statement."]','["st"]'),
('w_1140','testify','/ˈtestɪfaɪ/','verb','v. 作证','["test"]','["Testify in court."]','["test"]'),
('w_1141','testimony','/ˈtestɪməni/','noun','n. 证词','["test"]','["Witness testimony."]','["test"]'),
('w_1142','contest','/ˈkɒntest/','noun','n. 竞赛','["con","test"]','["Speech contest."]','["con","test"]'),
('w_1143','detest','/dɪˈtest/','verb','v. 厌恶','["de","test"]','["Detest violence."]','["de","test"]'),
('w_1144','protest','/ˈprəʊtest/','noun','n. 抗议','["pro","test"]','["Protest march."]','["pro","test"]'),
('w_1145','text','/tekst/','noun','n. 文本','["text"]','["Text message."]','["text"]'),
('w_1146','textile','/ˈtekstaɪl/','noun','n. 纺织品','["text"]','["Cotton textiles."]','["text"]'),
('w_1147','texture','/ˈtekstʃər/','noun','n. 质地','["text"]','["Fabric texture."]','["text"]'),
('w_1148','context','/ˈkɒntekst/','noun','n. 上下文','["con","text"]','["In context."]','["con","text"]'),
('w_1149','pretext','/ˈpriːtekst/','noun','n. 借口','["pre","text"]','["Under the pretext."]','["pre","text"]'),
('w_1150','detect','/dɪˈtekt/','verb','v. 发现','["de","tect"]','["Detect problems."]','["de","tect"]'),
('w_1151','detective','/dɪˈtektɪv/','noun','n. 侦探','["de","tect"]','["Private detective."]','["de","tect"]'),
('w_1152','protect','/prəˈtekt/','verb','v. 保护','["pro","tect"]','["Protect environment."]','["pro","tect"]'),
('w_1153','protection','/prəˈtekʃən/','noun','n. 保护','["pro","tect"]','["Consumer protection."]','["pro","tect"]'),
('w_1154','protective','/prəˈtektɪv/','adj','adj. 保护的','["pro","tect"]','["Protective measures."]','["pro","tect"]'),
('w_1155','architect','/ˈɑːkɪtekt/','noun','n. 建筑师','["archi","tect"]','["Software architect."]','["archi","tect"]'),
('w_1156','architecture','/ˈɑːkɪtektʃər/','noun','n. 建筑学','["archi","tect"]','["Modern architecture."]','["archi","tect"]'),
('w_1157','technique','/tekˈniːk/','noun','n. 技术','["techn"]','["New technique."]','["techn"]'),
('w_1158','technology','/tekˈnɒlədʒi/','noun','n. 技术','["techn","log"]','["Technology advances."]','["techn","log"]'),
('w_1159','technological','/ˌteknəˈlɒdʒɪkəl/','adj','adj. 技术的','["techn","log"]','["Technological innovation."]','["techn","log"]'),
('w_1160','technician','/tekˈnɪʃən/','noun','n. 技术员','["techn"]','["Lab technician."]','["techn"]'),
('w_1161','sympathy','/ˈsɪmpəθi/','noun','n. 同情','["sym","path"]','["Express sympathy."]','["sym","path"]'),
('w_1162','sympathetic','/ˌsɪmpəˈθetɪk/','adj','adj. 同情的','["sym","path"]','["Sympathetic attitude."]','["sym","path"]'),
('w_1163','empathy','/ˈempəθi/','noun','n. 同理心','["em","path"]','["Show empathy."]','["em","path"]'),
('w_1164','antipathy','/ænˈtɪpəθi/','noun','n. 厌恶','["anti","path"]','["Deep antipathy."]','["anti","path"]'),
('w_1165','apathy','/ˈæpəθi/','noun','n. 冷漠','["a","path"]','["Political apathy."]','["a","path"]'),
('w_1166','compatible','/kəmˈpætɪbl/','adj','adj. 兼容的','["com","pat"]','["Compatible with Windows."]','["com","pat"]'),
('w_1167','patience','/ˈpeɪʃəns/','noun','n. 耐心','["pat"]','["Have patience."]','["pat"]'),
('w_1168','patient','/ˈpeɪʃənt/','adj','adj. 耐心的','["pat"]','["Be patient."]','["pat"]'),
('w_1169','impatient','/ɪmˈpeɪʃənt/','adj','adj. 不耐烦的','["im","pat"]','["Impatient with delays."]','["im","pat"]'),
('w_1170','patron','/ˈpeɪtrən/','noun','n. 赞助人','["pat"]','["Patron of the arts."]','["pat"]'),
('w_1171','patriot','/ˈpeɪtriət/','noun','n. 爱国者','["pat"]','["A true patriot."]','["pat"]'),
('w_1172','patriotic','/ˌpeɪtriˈɒtɪk/','adj','adj. 爱国的','["pat"]','["Patriotic song."]','["pat"]'),
('w_1173','impair','/ɪmˈpeər/','verb','v. 损害','["im","pair"]','["Impair health."]','["im","pair"]'),
('w_1174','repair','/rɪˈpeər/','verb','v. 修理','["re","pair"]','["Repair the car."]','["re","pair"]'),
('w_1175','pair','/peər/','noun','n. 一对','["pair"]','["A pair of shoes."]','["pair"]'),
('w_1176','despair','/dɪˈspeər/','noun','n. 绝望','["de","spair"]','["Fall into despair."]','["de","spair"]'),
('w_1177','separate','/ˈsepərət/','adj','adj. 分开的','["se","par"]','["Live separate lives."]','["se","par"]'),
('w_1178','separate','/ˈsepəreɪt/','verb','v. 分开','["se","par"]','["Separate the components."]','["se","par"]'),
('w_1179','prepar','/prɪˈpeər/','verb','v. 准备','["pre","par"]','["Prepare dinner."]','["pre","par"]'),
('w_1180','preparation','/ˌprepəˈreɪʃən/','noun','n. 准备','["pre","par"]','["Preparation for exam."]','["pre","par"]'),
('w_1181','comparable','/ˈkɒmpərəbl/','adj','adj. 可比的','["com","par"]','["Comparable quality."]','["com","par"]'),
('w_1182','compare','/kəmˈpeər/','verb','v. 比较','["com","par"]','["Compare prices."]','["com","par"]'),
('w_1183','comparison','/kəmˈpærɪsən/','noun','n. 比较','["com","par"]','["Fair comparison."]','["com","par"]'),
('w_1184','disparity','/dɪˈspærɪti/','noun','n. 不平等','["dis","par"]','["Economic disparity."]','["dis","par"]'),
('w_1185','parity','/ˈpærɪti/','noun','n. 平等','["par"]','["Gender parity."]','["par"]'),
('w_1186','impart','/ɪmˈpɑːt/','verb','v. 传授','["im","part"]','["Impart knowledge."]','["im","part"]'),
('w_1187','part','/pɑːt/','noun','n. 部分','["part"]','["Part of the whole."]','["part"]'),
('w_1188','partial','/ˈpɑːʃəl/','adj','adj. 部分的','["part"]','["Partial payment."]','["part"]'),
('w_1189','participate','/pɑːˈtɪsɪpeɪt/','verb','v. 参与','["part","cip"]','["Participate in event."]','["part","cip"]'),
('w_1190','participant','/pɑːˈtɪsɪpənt/','noun','n. 参与者','["part","cip"]','["Event participant."]','["part","cip"]'),
('w_1191','particle','/ˈpɑːtɪkl/','noun','n. 粒子','["part"]','["Dust particles."]','["part"]'),
('w_1192','partner','/ˈpɑːtnər/','noun','n. 伙伴','["part"]','["Business partner."]','["part"]'),
('w_1193','apartment','/əˈpɑːtmənt/','noun','n. 公寓','["a","part"]','["City apartment."]','["a","part"]'),
('w_1194','department','/dɪˈpɑːtmənt/','noun','n. 部门','["de","part"]','["Sales department."]','["de","part"]'),
('w_1195','depart','/dɪˈpɑːt/','verb','v. 离开','["de","part"]','["Depart at noon."]','["de","part"]'),
('w_1196','departure','/dɪˈpɑːtʃər/','noun','n. 出发','["de","part"]','["Departure time."]','["de","part"]'),
('w_1197','particular','/pəˈtɪkjʊlər/','adj','adj. 特定的','["part"]','["In particular."]','["part"]'),
('w_1198','party','/ˈpɑːti/','noun','n. 政党','["part"]','["Political party."]','["part"]'),
('w_1199','passage','/ˈpæsɪdʒ/','noun','n. 通道','["pass"]','["Mountain passage."]','["pass"]'),
('w_1200','passenger','/ˈpæsɪndʒər/','noun','n. 乘客','["pass"]','["Train passenger."]','["pass"]');
