-- 添加词汇 801-900
INSERT INTO words (word_id, word, phonetic, pos, definition, family, examples, roots) VALUES
('w_0801','evoke','/ɪˈvəʊk/','verb','v. 引起','["e","vok"]','["Evoke memories."]','["e","vok"]'),
('w_0802','provoke','/prəˈvəʊk/','verb','v. 激怒','["pro","vok"]','["Provoke reaction."]','["pro","vok"]'),
('w_0803','revoke','/rɪˈvəʊk/','verb','v. 撤销','["re","vok"]','["Revoke license."]','["re","vok"]'),
('w_0804','convoke','/kənˈvəʊk/','verb','v. 召集','["con","vok"]','["Convoke parliament."]','["con","vok"]'),
('w_0805','vouch','/vaʊtʃ/','verb','v. 担保','["vouch"]','["Vouch for friend."]','["vouch"]'),
('w_0806','voucher','/ˈvaʊtʃər/','noun','n. 凭证','["vouch"]','["Gift voucher."]','["vouch"]'),
('w_0807','avouch','/əˈvaʊtʃ/','verb','v. 主张','["a","vouch"]','["Avouch truth."]','["a","vouch"]'),
('w_0808','devolve','/dɪˈvɒlv/','verb','v. 转移','["de","volv"]','["Devolve power."]','["de","volv"]'),
('w_0809','evolve','/ɪˈvɒlv/','verb','v. 进化','["e","volv"]','["Evolve species."]','["e","volv"]'),
('w_0810','involve','/ɪnˈvɒlv/','verb','v. 包含','["in","volv"]','["Involve costs."]','["in","volv"]'),
('w_0811','revolve','/rɪˈvɒlv/','verb','v. 旋转','["re","volv"]','["Revolve around sun."]','["re","volv"]'),
('w_0812','revolution','/ˌrevəˈluːʃən/','noun','n. 革命','["re","volv"]','["Industrial revolution."]','["re","volv"]'),
('w_0813','revolver','/rɪˈvɒlvər/','noun','n. 左轮手枪','["re","volv"]','["Western revolver."]','["re","volv"]'),
('w_0814','volume','/ˈvɒljuːm/','noun','n. 体积','["vol"]','["Sales volume."]','["vol"]'),
('w_0815','voluminous','/vəˈluːmɪnəs/','adj','adj. 容积大的','["vol"]','["Voluminous data."]','["vol"]'),
('w_0816','volunteer','/ˌvɒlənˈtɪər/','noun','n. 志愿者','["vol"]','["Community volunteer."]','["vol"]'),
('w_0817','benevolent','/bɪˈnevələnt/','adj','adj. 慈善的','["bene","vol"]','["Benevolent donor."]','["bene","vol"]'),
('w_0818','volition','/vəˈlɪʃən/','noun','n. 意志','["vol"]','["Free will."]','["vol"]'),
('w_0819','willing','/ˈwɪlɪŋ/','adj','adj. 愿意的','["will"]','["Willing participant."]','["will"]'),
('w_0820','unwilling','/ʌnˈwɪlɪŋ/','adj','adj. 不愿意的','["un","will"]','["Unwilling to help."]','["un","will"]'),
('w_0821','willful','/ˈwɪlfʊl/','adj','adj. 故意的','["will"]','["Willful misconduct."]','["will"]'),
('w_0822','willpower','/ˈwɪlpaʊər/','noun','n. 意志力','["will","power"]','["Strong willpower."]','["will","power"]'),
('w_0823','voluntary','/ˈvɒləntəri/','adj','adj. 自愿的','["vol"]','["Voluntary work."]','["vol"]'),
('w_0824','involuntary','/ɪnˈvɒləntəri/','adj','adj. 非自愿的','["in","vol"]','["Involuntary action."]','["in","vol"]'),
('w_0825','volunteer','/ˌvɒlənˈtɪər/','verb','v. 自愿','["vol"]','["Volunteer services."]','["vol"]'),
('w_0826','vouchsafe','/vaʊtʃˈseɪf/','verb','v. 赐予','["vouch","safe"]','["Vouchsafe reply."]','["vouch","safe"]'),
('w_0827','vow','/vaʊ/','noun','n. 誓言','["vow"]','["Marriage vow."]','["vow"]'),
('w_0828','vowel','/ˈvaʊəl/','noun','n. 元音','["vow"]','["English vowels."]','["vow"]'),
('w_0829','devour','/dɪˈvaʊər/','verb','v. 吞食','["de","vour"]','["Devour books."]','["de","vour"]'),
('w_0830','vorous','/vərəs/','suffix','suffix. 食...的','["vor"]','["Carnivorous."]','["vor"]'),
('w_0831','voracious','/vəˈreɪʃəs/','adj','adj. 贪婪的','["vor"]','["Voracious reader."]','["vor"]'),
('w_0832','omnivore','/ˈɒmnɪvɔːr/','noun','n. 杂食动物','["omni","vor"]','["Humans are omnivores."]','["omni","vor"]'),
('w_0833','herbivore','/ˈhɜːbɪvɔːr/','noun','n. 食草动物','["herbi","vor"]','["Cow is herbivore."]','["herbi","vor"]'),
('w_0834','carnivore','/ˈkɑːnɪvɔːr/','noun','n. 食肉动物','["carni","vor"]','["Lion is carnivore."]','["carni","vor"]'),
('w_0835','vulgar','/ˈvʌlɡər/','adj','adj. 粗俗的','["vulg"]','["Vulgar language."]','["vulg"]'),
('w_0836','vulnerability','/ˌvʌlnərəˈbɪlɪti/','noun','n. 脆弱性','["vuln"]','["Security vulnerability."]','["vuln"]'),
('w_0837','vulnerable','/ˈvʌlnərəbl/','adj','adj. 脆弱的','["vuln"]','["Vulnerable groups."]','["vuln"]'),
('w_0838','vulcanize','/ˈvʌlkənaɪz/','verb','v. 硫化','["vulc"]','["Vulcanize rubber."]','["vulc"]'),
('w_0839','vouch','/vaʊtʃ/','verb','v. 担保','["vouch"]','["Vouch for quality."]','["vouch"]'),
('w_0840','vowel','/ˈvaʊəl/','noun','n. 母音','["vow"]','["Front vowel."]','["vow"]'),
('w_0841','waive','/weɪv/','verb','v. 放弃','["waiv"]','["Waive rights."]','["waiv"]'),
('w_0842','waiver','/ˈweɪvər/','noun','n. 弃权书','["waiv"]','["Sign waiver."]','["waiv"]'),
('w_0843','wavier','/ˈweɪviər/','adj','adj. 摇摆的','["wav"]','["Wavier line."]','["wav"]'),
('w_0844','wave','/weɪv/','noun','n. 波浪','["wav"]','["Sound wave."]','["wav"]'),
('w_0845','wavy','/ˈweɪvi/','adj','adj. 波状的','["wav"]','["Wavy hair."]','["wav"]'),
('w_0846','warm','/wɔːm/','adj','adj. 温暖的','["warm"]','["Warm weather."]','["warm"]'),
('w_0847','warmth','/wɔːmθ/','noun','n. 温暖','["warm"]','["Sun warmth."]','["warm"]'),
('w_0848','swarm','/swɔːm/','noun','n. 蜂群','["swarm"]','["Bee swarm."]','["swarm"]'),
('w_0849','storm','/stɔːm/','noun','n. 暴风雨','["storm"]','["Thunderstorm."]','["storm"]'),
('w_0850','stormy','/ˈstɔːmi/','adj','adj. 暴风雨的','["storm"]','["Stormy weather."]','["storm"]'),
('w_0851','warm','/wɔːm/','verb','v. 加热','["warm"]','["Warm the room."]','["warm"]'),
('w_0852','warmonger','/ˈwɔːmʌŋɡər/','noun','n. 战争贩子','["war","monger"]','["Warmonger propaganda."]','["war","monger"]'),
('w_0853','warfare','/ˈwɔːfeər/','noun','n. 战争','["war"]','["Modern warfare."]','["war"]'),
('w_0854','warlike','/ˈwɔːlaɪk/','adj','adj. 好战的','["war"]','["Warlike nation."]','["war"]'),
('w_0855','warrant','/ˈwɒrənt/','noun','n. 授权令','["war"]','["Search warrant."]','["war"]'),
('w_0856','warranty','/ˈwɒrənti/','noun','n. 保修单','["war"]','["Product warranty."]','["war"]'),
('w_0857','guarantee','/ˌɡærənˈtiː/','noun','n. 保证','["guarant"]','["Money-back guarantee."]','["guarant"]'),
('w_0858','guard','/ɡɑːd/','verb','v. 守卫','["guard"]','["Guard the door."]','["guard"]'),
('w_0859','guardian','/ˈɡɑːdiən/','noun','n. 监护人','["guard"]','["Legal guardian."]','["guard"]'),
('w_0860','regard','/rɪˈɡɑːd/','verb','v. 看待','["re","gard"]','["Regard as important."]','["re","gard"]'),
('w_0861','regardless','/rɪˈɡɑːdləs/','adv','adv. 不管','["re","gard"]','["Regardless of weather."]','["re","gard"]'),
('w_0862','disregard','/ˌdɪsrɪˈɡɑːd/','verb','v. 忽视','["dis","re","gard"]','["Disregard rules."]','["dis","re","gard"]'),
('w_0863','wardrobe','/ˈwɔːdrəʊb/','noun','n. 衣柜','["ward","robe"]','["Empty wardrobe."]','["ward","robe"]'),
('w_0864','ward','/wɔːd/','noun','n. 病房','["ward"]','["Hospital ward."]','["ward"]'),
('w_0865','award','/əˈwɔːd/','noun','n. 奖项','["a","ward"]','["Academy Award."]','["a","ward"]'),
('w_0866','reward','/rɪˈwɔːd/','noun','n. 奖励','["re","ward"]','["Cash reward."]','["re","ward"]'),
('w_0867','toward','/təˈwɔːd/','prep','prep. 向','["to","ward"]','["Walk toward."]','["to","ward"]'),
('w_0868','forward','/ˈfɔːwəd/','adv','adv. 向前','["fore","ward"]','["Move forward."]','["fore","ward"]'),
('w_0869','backward','/ˈbækwəd/','adv','adv. 向后','["back","ward"]','["Step backward."]','["back","ward"]'),
('w_0870','upward','/ˈʌpwəd/','adv','adv. 向上','["up","ward"]','["Look upward."]','["up","ward"]'),
('w_0871','downward','/ˈdaʊnwəd/','adv','adv. 向下','["down","ward"]','["Slide downward."]','["down","ward"]'),
('w_0872','wayward','/ˈweɪwəd/','adj','adj. 任性的','["way","ward"]','["Wayward child."]','["way","ward"]'),
('w_0873','steward','/ˈstjuːwəd/','noun','n. 管家','["stew","ard"]','["Ship steward."]','["stew","ard"]'),
('w_0874','stewardess','/ˌstjuːwəˈdes/','noun','n. 空姐','["stew","ard"]','["Air stewardess."]','["stew","ard"]'),
('w_0875','wield','/wiːld/','verb','v. 挥动','["wield"]','["Wield power."]','["wield"]'),
('w_0876','wieldy','/ˈwiːldi/','adj','adj. 易处理的','["wield"]','["Wieldy tool."]','["wield"]'),
('w_0877','unwieldy','/ʌnˈwiːldi/','adj','adj. 笨重的','["un","wield"]','["Unwieldy package."]','["un","wield"]'),
('w_0878','world','/wɜːld/','noun','n. 世界','["world"]','["World peace."]','["world"]'),
('w_0879','worldly','/ˈwɜːldli/','adj','adj. 世间的','["world"]','["Worldly affairs."]','["world"]'),
('w_0880','worldwide','/ˈwɜːldwaɪd/','adj','adj. 全球的','["world","wide"]','["Worldwide problem."]','["world","wide"]'),
('w_0881','whirl','/wɜːl/','verb','v. 旋转','["whirl"]','["Whirl around."]','["whirl"]'),
('w_0882','whirlwind','/ˈwɜːlwɪnd/','noun','n. 旋风','["whirl","wind"]','["Whirlwind romance."]','["whirl","wind"]'),
('w_0883','whisper','/ˈwɪspər/','verb','v. 低语','["whisp"]','["Whisper secrets."]','["whisp"]'),
('w_0884','whistle','/ˈwɪsl/','verb','v. 吹口哨','["whistl"]','["Whistle a song."]','["whistl"]'),
('w_0885','whim','/wɪm/','noun','n. 冲动','["whim"]','["On a whim."]','["whim"]'),
('w_0886','whimper','/ˈwɪmpər/','verb','v. 啜泣','["whimp"]','["Whimper quietly."]','["whimp"]'),
('w_0887','whine','/waɪn/','verb','v. 发牢骚','["whin"]','["Whine about food."]','["whin"]'),
('w_0888','whip','/wɪp/','noun','n. 鞭子','["whip"]','["Crack whip."]','["whip"]'),
('w_0889','whisk','/wɪsk/','verb','v. 挥动','["whisk"]','["Whisk eggs."]','["whisk"]'),
('w_0890','whiskers','/ˈwɪskərz/','noun','n. 胡须','["whisk"]','["Cat whiskers."]','["whisk"]'),
('w_0891','whisker','/ˈwɪskər/','noun','n. 须','["whisk"]','["One whisker."]','["whisk"]'),
('w_0892','wince','/wɪns/','verb','v. 退缩','["wince"]','["Wince in pain."]','["wince"]'),
('w_0893','winch','/wɪntʃ/','noun','n. 绞盘','["winc"]','["Pull with winch."]','["winc"]'),
('w_0894','wind','/wɪnd/','noun','n. 风','["wind"]','["Strong wind."]','["wind"]'),
('w_0895','windy','/ˈwɪndi/','adj','adj. 多风的','["wind"]','["Windy day."]','["wind"]'),
('w_0896','window','/ˈwɪndəʊ/','noun','n. 窗户','["wind","ow"]','["Open window."]','["wind","ow"]'),
('w_0897','winder','/ˈwaɪndər/','noun','n. 卷轴','["wind"]','["Key winder."]','["wind"]'),
('w_0898','windmill','/ˈwɪndmɪl/','noun','n. 风车','["wind","mill"]','["Traditional windmill."]','["wind","mill"]'),
('w_0899','windpipe','/ˈwɪndpaɪp/','noun','n. 气管','["wind","pipe"]','["Block windpipe."]','["wind","pipe"]'),
('w_0900','windbreak','/ˈwɪndbreɪk/','noun','n. 防风林','["wind","break"]','["Plant windbreak."]','["wind","break"]');
