-- 添加词汇 301-400
INSERT INTO words (word_id, word, phonetic, pos, definition, family, examples, roots) VALUES
('w_0301','visual','/ˈvɪʒʊəl/','adj','adj. 视觉的','[]','["Visual arts."]','["vis"]'),
('w_0302','advise','/ədˈvaɪz/','verb','v. 建议','[]','["Advise caution."]','["ad","vis"]'),
('w_0303','devise','/dɪˈvaɪz/','verb','v. 设计','[]','["Devise a plan."]','["de","vis"]'),
('w_0304','division','/dɪˈvɪʒən/','noun','n. 分开','[]','["Cell division."]','["di","vis"]'),
('w_0305','television','/ˈtelɪvɪʒən/','noun','n. 电视','[]','["Watch television."]','["tele","vis"]'),
('w_0306','provide','/prəˈvaɪd/','verb','v. 提供','[]','["Provide assistance."]','["pro","vid"]'),
('w_0307','evidence','/ˈevɪdəns/','noun','n. 证据','[]','["Physical evidence."]','["e","vid"]'),
('w_0308','evident','/ˈevɪdənt/','adj','adj. 明显的','[]','["Evident success."]','["e","vid"]'),
('w_0309','obvious','/ˈɒbvɪəs/','adj','adj. 显然的','[]','["Obvious error."]','["ob","vi"]'),
('w_0310','previous','/ˈpriːvɪəs/','adj','adj. 以前的','[]','["Previous day."]','["pre","vi"]'),
('w_0311','improve','/ɪmˈpruːv/','verb','v. 改进','[]','["Improve skills."]','["im","prov"]'),
('w_0312','approve','/əˈpruːv/','verb','v. 批准','[]','["Approve the budget."]','["ap","prov"]'),
('w_0313','disapprove','/ˌdɪsəˈpruːv/','verb','v. 不赞成','[]','["Disapprove the plan."]','["dis","ap","prov"]'),
('w_0314','proof','/pruːf/','noun','n. 证据','[]','["Proof of identity."]','["prov"]'),
('w_0315','approve','/əˈpruːv/','verb','v. 认可','[]','["Board approved."]','["ap"]'),
('w_0316','reaction','/riˈækʃən/','noun','n. 反应','[]','["Chemical reaction."]','["re","act"]'),
('w_0317','action','/ˈækʃən/','noun','n. 行动','[]','["Take action."]','["act"]'),
('w_0318','active','/ˈæktɪv/','adj','adj. 积极的','[]','["Active lifestyle."]','["act"]'),
('w_0319','activity','/ækˈtɪvɪti/','noun','n. 活动','[]','["Outdoor activities."]','["act"]'),
('w_0320','interact','/ˌɪntəˈækt/','verb','v. 互动','[]','["Interact with friends."]','["inter","act"]'),
('w_0321','react','/riˈækt/','verb','v. 反应','[]','["React quickly."]','["re","act"]'),
('w_0322','exact','/ɪɡˈzækt/','adj','adj. 精确的','[]','["Exact time."]','["ex","act"]'),
('w_0323','exactly','/ɪɡˈzæktli/','adv','adv. 精确地','[]','["Exactly right."]','["ex","act"]'),
('w_0324','interact','/ˌɪntəˈækt/','verb','v. 相互作用','[]','["Chemicals interact."]','["inter"]'),
('w_0325','enact','/ɪˈnækt/','verb','v. 制定','[]','["Enact laws."]','["e","nact"]'),
('w_0326','practice','/ˈpræktɪs/','noun','n. 练习','[]','["Practice makes perfect."]','["pract"]'),
('w_0327','practical','/ˈpræktɪkəl/','adj','adj. 实际的','[]','["Practical solution."]','["pract"]'),
('w_0328','practitioner','/prækˈtɪʃənər/','noun','n. 从业者','[]','["Medical practitioner."]','["pract"]'),
('w_0329','alliance','/əˈlaɪəns/','noun','n. 联盟','[]','["Strategic alliance."]','["al","li"]'),
('w_0330','allied','/ˈælaɪd/','adj','adj. 联合的','[]','["Allied forces."]','["al","ly"]'),
('w_0331','ally','/ˈælaɪ/','noun','n. 同盟国','[]','["NATO allies."]','["al","ly"]'),
('w_0332','allocate','/ˈæləkeɪt/','verb','v. 分配','[]','["Allocate resources."]','["al","loc"]'),
('w_0333','allow','/əˈlaʊ/','verb','v. 允许','[]','["Allow entry."]','["al","low"]'),
('w_0334','alloy','/ˈælɔɪ/','noun','n. 合金','[]','["Steel alloy."]','["al","loy"]'),
('w_0335','alleviate','/əˈliːvɪeɪt/','verb','v. 减轻','[]','["Alleviate pain."]','["al","lev"]'),
('w_0336','allure','/əˈljʊər/','noun','n. 吸引力','[]','["The allure of travel."]','["al","lure"]'),
('w_0337','allude','/əˈljuːd/','verb','v. 暗指','[]','["Allude to something."]','["al","lude"]'),
('w_0338','collude','/kəˈljuːd/','verb','v. 勾结','[]','["Collude with rivals."]','["col","lude"]'),
('w_0339','elude','/ɪˈljuːd/','verb','v. 逃避','[]','["Elude capture."]','["e","lude"]'),
('w_0340','delude','/dɪˈljuːd/','verb','v. 欺骗','[]','["Delude yourself."]','["de","lude"]'),
('w_0341','allusion','/əˈljuːʒən/','noun','n. 典故','[]','["Literary allusion."]','["al","lu"]'),
('w_0342','illusion','/ɪˈljuːʒən/','noun','n. 幻觉','[]','["Optical illusion."]','["il","lu"]'),
('w_0343','ambition','/æmˈbɪʃən/','noun','n. 雄心','[]','["Career ambition."]','["amb","it"]'),
('w_0344','ambient','/ˈæmbiənt/','adj','adj. 周围的','[]','["Ambient temperature."]','["amb","ient"]'),
('w_0345','ambiguous','/æmˈbɪɡjʊəs/','adj','adj. 模糊的','[]','["Ambiguous statement."]','["amb","ig"]'),
('w_0346','ambivalent','/æmˈbɪvələnt/','adj','adj. 矛盾的','[]','["Ambivalent feelings."]','["amb","val"]'),
('w_0347','circumstance','/ˈsɜːkəmstəns/','noun','n. 情况','[]','["Under circumstances."]','["circum","st"]'),
('w_0348','constant','/ˈkɒnstənt/','adj','adj. 恒定的','[]','["Constant speed."]','["con","st"]'),
('w_0349','distant','/ˈdɪstənt/','adj','adj. 遥远的','[]','["Distant relative."]','["dis","st"]'),
('w_0350','instant','/ˈɪnstənt/','adj','adj. 立即的','[]','["Instant noodles."]','["in","st"]'),
('w_0351','substance','/ˈsʌbstəns/','noun','n. 物质','[]','["Chemical substance."]','["sub","st"]'),
('w_0352','substantial','/səbˈstænʃəl/','adj','adj. 大量的','[]','["Substantial progress."]','["sub","st"]'),
('w_0353','substitute','/ˈsʌbstɪtjuːt/','verb','v. 替代','[]','["Substitute for sugar."]','["sub","st"]'),
('w_0354','obstacle','/ˈɒbstəkl/','noun','n. 障碍','[]','["Obstacle to success."]','["ob","st"]'),
('w_0355','stable','/ˈsteɪbl/','adj','adj. 稳定的','[]','["Stable economy."]','["st"]'),
('w_0356','stability','/stəˈbɪlɪti/','noun','n. 稳定性','[]','["Political stability."]','["st"]'),
('w_0357','stabilize','/ˈsteɪbɪlaɪz/','verb','v. 使稳定','[]','["Stabilize prices."]','["st"]'),
('w_0358','estate','/ɪˈsteɪt/','noun','n. 房产','[]','["Real estate."]','["e","st"]'),
('w_0359','status','/ˈsteɪtəs/','noun','n. 地位','[]','["Social status."]','["st"]'),
('w_0360','statute','/ˈstætʃuːt/','noun','n. 法规','[]','["Statute of limitations."]','["st"]'),
('w_0361','state','/steɪt/','noun','n. 州','[]','["State government."]','["st"]'),
('w_0362','statement','/ˈsteɪtmənt/','noun','n. 声明','[]','["Official statement."]','["st"]'),
('w_0363','statesman','/ˈsteɪtsmən/','noun','n. 政治家','[]','["Respected statesman."]','["st"]'),
('w_0364','stationary','/ˈsteɪʃənəri/','adj','adj. 静止的','[]','["Stationary object."]','["st"]'),
('w_0365','stationery','/ˈsteɪʃənəri/','noun','n. 文具','[]','["Stationery shop."]','["st"]'),
('w_0366','substation','/ˈsʌbsteɪʃən/','noun','n. 变电站','[]','["Power substation."]','["sub","st"]'),
('w_0367','testify','/ˈtestɪfaɪ/','verb','v. 作证','[]','["Testify in court."]','["test"]'),
('w_0368','testimony','/ˈtestɪməni/','noun','n. 证词','[]','["Witness testimony."]','["test"]'),
('w_0369','contest','/ˈkɒntest/','noun','n. 竞赛','[]','["Speech contest."]','["con","test"]'),
('w_0370','contest','/kənˈtest/','verb','v. 争夺','[]','["Contest the decision."]','["con","test"]'),
('w_0371','detest','/dɪˈtest/','verb','v. 厌恶','[]','["Detest violence."]','["de","test"]'),
('w_0372','protest','/ˈprəʊtest/','noun','n. 抗议','[]','["Protest march."]','["pro","test"]'),
('w_0373','text','/tekst/','noun','n. 文本','[]','["Text message."]','["text"]'),
('w_0374','textile','/ˈtekstaɪl/','noun','n. 纺织品','[]','["Cotton textiles."]','["text"]'),
('w_0375','texture','/ˈtekstʃər/','noun','n. 质地','[]','["Fabric texture."]','["text"]'),
('w_0376','context','/ˈkɒntekst/','noun','n. 上下文','[]','["In context."]','["con","text"]'),
('w_0377','pretext','/ˈpriːtekst/','noun','n. 借口','[]','["Under the pretext."]','["pre","text"]'),
('w_0378','intertext','/ˈɪntətekst/','noun','n. 文本关系','[]','["Intertextuality."]','["inter","text"]'),
('w_0379','test','/test/','noun','n. 测试','[]','["Pop test."]','["test"]'),
('w_0380','protester','/prəˈtestər/','noun','n. 抗议者','[]','["Protesters gathered."]','["pro","test"]'),
('w_0381','detectable','/dɪˈtektəbl/','adj','adj. 可检测的','[]','["Detectable signal."]','["de","tect"]'),
('w_0382','protect','/prəˈtekt/','verb','v. 保护','[]','["Protect environment."]','["pro","tect"]'),
('w_0383','protection','/prəˈtekʃən/','noun','n. 保护','[]','["Consumer protection."]','["pro","tect"]'),
('w_0384','protective','/prəˈtektɪv/','adj','adj. 保护的','[]','["Protective measures."]','["pro","tect"]'),
('w_0385','architect','/ˈɑːkɪtekt/','noun','n. 建筑师','[]','["Software architect."]','["archi","tect"]'),
('w_0386','architecture','/ˈɑːkɪtektʃər/','noun','n. 建筑学','[]','["Modern architecture."]','["archi","tect"]'),
('w_0387','detect','/dɪˈtekt/','verb','v. 发现','[]','["Detect problems."]','["de","tect"]'),
('w_0388','detective','/dɪˈtektɪv/','noun','n. 侦探','[]','["Private detective."]','["de","tect"]'),
('w_0389','technique','/tekˈniːk/','noun','n. 技术','[]','["New technique."]','["techn"]'),
('w_0390','technology','/tekˈnɒlədʒi/','noun','n. 技术','[]','["Technology advances."]','["techn","log"]'),
('w_0391','technological','/ˌteknəˈlɒdʒɪkəl/','adj','adj. 技术的','[]','["Technological innovation."]','["techn","log"]'),
('w_0392','technician','/tekˈnɪʃən/','noun','n. 技术员','[]','["Lab technician."]','["techn"]'),
('w_0393','aesthetic','/iːsˈθetɪk/','adj','adj. 美学的','[]','["Aesthetic appeal."]','["esthes"]'),
('w_0394','anesthetic','/ˌænɪsˈθetɪk/','noun','n. 麻醉剂','[]','["Local anesthetic."]','["an","esthes"]'),
('w_0395','synthetic','/sɪnˈθetɪk/','adj','adj. 合成的','[]','["Synthetic materials."]','["syn","thet"]'),
('w_0396','sympathy','/ˈsɪmpəθi/','noun','n. 同情','[]','["Express sympathy."]','["sym","path"]'),
('w_0397','sympathetic','/ˌsɪmpəˈθetɪk/','adj','adj. 同情的','[]','["Sympathetic attitude."]','["sym","path"]'),
('w_0398','empathy','/ˈempəθi/','noun','n. 同理心','[]','["Show empathy."]','["em","path"]'),
('w_0399','antipathy','/ænˈtɪpəθi/','noun','n. 厌恶','[]','["Deep antipathy."]','["anti","path"]'),
('w_0400','apathy','/ˈæpəθi/','noun','n. 冷漠','[]','["Political apathy."]','["a","path"]');
