-- 添加词汇 501-600
INSERT INTO words (word_id, word, phonetic, pos, definition, family, examples, roots) VALUES
('w_0501','comply','/kəmˈplaɪ/','verb','v. 遵守','["comply"]','["All companies must comply with regulations."]','["com","ply"]'),
('w_0502','implement','/ˈɪmplɪmənt/','verb','v. 实施','["implement"]','["Implement the new policy."]','["im","ple"]'),
('w_0503','supplement','/ˈsʌplɪmənt/','noun','n. 补充物','["supplement"]','["Vitamin supplement."]','["sup","ple"]'),
('w_0504','explicit','/ɪkˈsplɪsɪt/','adj','adj. 明确的','["explicit"]','["Explicit instructions."]','["ex","plic"]'),
('w_0505','implicit','/ɪmˈplɪsɪt/','adj','adj. 含蓄的','["implicit"]','["Implicit trust."]','["im","plic"]'),
('w_0506','explicate','/ˈeksplɪkeɪt/','verb','v. 详细说明','["explicate"]','["Explicate the theory."]','["ex","plic"]'),
('w_0507','complicate','/ˈkɒmplɪkeɪt/','verb','v. 使复杂','["complicate"]','["Complicate matters."]','["com","plic"]'),
('w_0508','duplicate','/ˈdjuːplɪkət/','verb','v. 复制','["duplicate"]','["Duplicate the document."]','["dupli"]'),
('w_0509','replicate','/ˈreplɪkeɪt/','verb','v. 复制','["replicate"]','["Replicate the experiment."]','["re","plic"]'),
('w_0510','implication','/ˌɪmplɪˈkeɪʃən/','noun','n. 含义','["implication"]','["Political implications."]','["im","plic"]'),
('w_0511','constitute','/ˈkɒnstɪtjuːt/','verb','v. 构成','["constitute"]','["Constitute a crime."]','["con","stit"]'),
('w_0512','constitution','/ˌkɒnstɪˈtjuːʃən/','noun','n. 宪法','["constitution"]','["The Constitution."]','["con","stit"]'),
('w_0513','institute','/ˈɪnstɪtjuːt/','noun','n. 机构','["institute"]','["Research institute."]','["in","stit"]'),
('w_0514','substitute','/ˈsʌbstɪtjuːt/','verb','v. 替代','["substitute"]','["Substitute for sugar."]','["sub","stit"]'),
('w_0515','destitute','/ˈdestɪtjuːt/','adj','adj. 贫困的','["destitute"]','["Destitute families."]','["de","stit"]'),
('w_0516','constitute','/ˈkɒnstɪtjuːt/','verb','v. 任命','["constitute"]','["Constitute a committee."]','["con"]'),
('w_0517','correspond','/ˌkɒrɪˈspɒnd/','verb','v. 符合','["correspond"]','["Correspond with expectations."]','["cor","respond"]'),
('w_0518','correspondence','/ˌkɒrɪˈspɒndəns/','noun','n. 通信','["correspondence"]','["Business correspondence."]','["cor","respond"]'),
('w_0519','respond','/rɪˈspɒnd/','verb','v. 回应','["respond"]','["Respond to questions."]','["re","spond"]'),
('w_0520','response','/rɪˈspɒns/','noun','n. 回应','["response"]','["Immediate response."]','["re","spons"]'),
('w_0521','responsible','/rɪˈspɒnsəbl/','adj','adj. 负责的','["responsible"]','["Responsible for outcomes."]','["re","spons"]'),
('w_0522','correspond','/ˌkɒrɪˈspɒnd/','verb','v. 通信','["correspond"]','["Correspond with friends."]','["cor"]'),
('w_0523','sponsor','/ˈspɒnsər/','noun','n. 赞助商','["sponsor"]','["Event sponsor."]','["spons"]'),
('w_0524','spontaneous','/spɒnˈteɪniəs/','adj','adj. 自发的','["spontaneous"]','["Spontaneous applause."]','["spon"]'),
('w_0525','transplant','/trænsˈplɑːnt/','verb','v. 移植','["transplant"]','["Transplant organs."]','["trans","plant"]'),
('w_0526','plantation','/plænˈteɪʃən/','noun','n. 种植园','["plantation"]','["Coffee plantation."]','["plant"]'),
('w_0527','implant','/ɪmˈplɑːnt/','verb','v. 植入','["implant"]','["Implant a device."]','["im","plant"]'),
('w_0528','complaint','/kəmˈpleɪnt/','noun','n. 投诉','["complaint"]','["File a complaint."]','["com","plain"]'),
('w_0529','complacent','/kəmˈpleɪsənt/','adj','adj. 自满的','["complacent"]','["Become complacent."]','["com","plac"]'),
('w_0530','placid','/ˈplæsɪd/','adj','adj. 平静的','["placid"]','["Placid lake."]','["plac"]'),
('w_0531','placebo','/pləˈsiːbəʊ/','noun','n. 安慰剂','["placebo"]','["Placebo effect."]','["plac"]'),
('w_0532','displace','/dɪsˈpleɪs/','verb','v. 取代','["displace"]','["Displace workers."]','["dis","place"]'),
('w_0533','replace','/rɪˈpleɪs/','verb','v. 替换','["replace"]','["Replace the battery."]','["re","place"]'),
('w_0534','displace','/dɪsˈpleɪs/','verb','v. 移动','["displace"]','["Displace the furniture."]','["dis"]'),
('w_0535','maintain','/meɪnˈteɪn/','verb','v. 维护','["maintain"]','["Maintain equipment."]','["main","tain"]'),
('w_0536','retain','/rɪˈteɪn/','verb','v. 保留','["retain"]','["Retain information."]','["re","tain"]'),
('w_0537','attain','/əˈteɪn/','verb','v. 获得','["attain"]','["Attain success."]','["at","tain"]'),
('w_0538','obtain','/əbˈteɪn/','verb','v. 获得','["obtain"]','["Obtain permission."]','["ob","tain"]'),
('w_0539','contain','/kənˈteɪn/','verb','v. 包含','["contain"]','["Contain information."]','["con","tain"]'),
('w_0540','sustain','/səˈsteɪn/','verb','v. 维持','["sustain"]','["Sustain growth."]','["sus","tain"]'),
('w_0541','abstain','/əbˈsteɪn/','verb','v. 戒除','["abstain"]','["Abstain from voting."]','["abs","tain"]'),
('w_0542','detain','/dɪˈteɪn/','verb','v. 拘留','["detain"]','["Detain suspects."]','["de","tain"]'),
('w_0543','retain','/rɪˈteɪn/','verb','v. 记住','["retain"]','["Retain memories."]','["re"]'),
('w_0544','attain','/əˈteɪn/','verb','v. 达到','["attain"]','["Attain goals."]','["at"]'),
('w_0545','continual','/kənˈtɪnjʊəl/','adj','adj. 连续的','["continual"]','["Continual improvement."]','["con","tin"]'),
('w_0546','continue','/kənˈtɪnjuː/','verb','v. 继续','["continue"]','["Continue working."]','["con","tin"]'),
('w_0547','continuous','/kənˈtɪnjʊəs/','adj','adj. 持续的','["continuous"]','["Continuous flow."]','["con","tin"]'),
('w_0548','continent','/ˈkɒntɪnənt/','noun','n. 大陆','["continent"]','["Asian continent."]','["con","tin"]'),
('w_0549','content','/kənˈtent/','adj','adj. 满足的','["content"]','["Content with life."]','["con","tent"]'),
('w_0550','contend','/kənˈtend/','verb','v. 竞争','["contend"]','["Contend for prizes."]','["con","tend"]'),
('w_0551','intend','/ɪnˈtend/','verb','v. 打算','["intend"]','["Intend to travel."]','["in","tend"]'),
('w_0552','intent','/ɪnˈtent/','noun','n. 意图','["intent"]','["Criminal intent."]','["in","tent"]'),
('w_0553','intense','/ɪnˈtens/','adj','adj. 强烈的','["intense"]','["Intense heat."]','["in","tens"]'),
('w_0554','intensive','/ɪnˈtensɪv/','adj','adj. 加强的','["intensive"]','["Intensive training."]','["in","tens"]'),
('w_0555','tense','/tens/','adj','adj. 紧张的','["tense"]','["Tense situation."]','["tens"]'),
('w_0556','tension','/ˈtenʃən/','noun','n. 紧张','["tension"]','["Political tension."]','["tens"]'),
('w_0557','extend','/ɪkˈstend/','verb','v. 延伸','["extend"]','["Extend the deadline."]','["ex","tend"]'),
('w_0558','extent','/ɪkˈstent/','noun','n. 程度','["extent"]','["To some extent."]','["ex","tent"]'),
('w_0559','portend','/pɔːˈtend/','verb','v. 预示','["portend"]','["Portend disaster."]','["por","tend"]'),
('w_0560','pretend','/prɪˈtend/','verb','v. 假装','["pretend"]','["Pretend to be happy."]','["pre","tend"]'),
('w_0561','tend','/tend/','verb','v. 倾向','["tend"]','["Tend to agree."]','["tend"]'),
('w_0562','tendency','/ˈtendənsi/','noun','n. 趋势','["tendency"]','["Market tendency."]','["tend"]'),
('w_0563','tentative','/ˈtentətɪv/','adj','adj. 暂定的','["tentative"]','["Tentative plan."]','["tent"]'),
('w_0564','attend','/əˈtend/','verb','v. 参加','["attend"]','["Attend a meeting."]','["at","tend"]'),
('w_0565','contend','/kənˈtend/','verb','v. 主张','["contend"]','["Contend that it is true."]','["con"]'),
('w_0566','distend','/dɪˈstend/','verb','v. 扩张','["distend"]','["Distend the stomach."]','["dis","tend"]'),
('w_0567','ostensible','/ɒˈstensɪbl/','adj','adj. 表面的','["ostensible"]','["Ostensible purpose."]','["os","tens"]'),
('w_0568','ostentatious','/ˌɒstenˈteɪʃəs/','adj','adj. 炫耀的','["ostentatious"]','["Ostentatious display."]','["os","tent"]'),
('w_0569','attend','/əˈtend/','verb','v. 注意','["attend"]','["Attend to details."]','["at"]'),
('w_0570','attorney','/əˈtɜːni/','noun','n. 律师','["attorney"]','["Defense attorney."]','["at","torn"]'),
('w_0571','turn','/tɜːn/','verb','v. 转动','["turn"]','["Turn around."]','["turn"]'),
('w_0572','return','/rɪˈtɜːn/','verb','v. 返回','["return"]','["Return home."]','["re","turn"]'),
('w_0573','turnout','/ˈtɜːnaʊt/','noun','n. 出席人数','["turnout"]','["High voter turnout."]','["turn"]'),
('w_0574','turnover','/ˈtɜːnəʊvər/','noun','n. 营业额','["turnover"]','["Annual turnover."]','["turn"]'),
('w_0575','distort','/dɪˈstɔːt/','verb','v. 扭曲','["distort"]','["Distort facts."]','["dis","tort"]'),
('w_0576','torture','/ˈtɔːtʃər/','noun','n. 折磨','["torture"]','["Psychological torture."]','["tort"]'),
('w_0577','tortuous','/ˈtɔːtʃʊəs/','adj','adj. 曲折的','["tortuous"]','["Tortuous path."]','["tort"]'),
('w_0578','contort','/kənˈtɔːt/','verb','v. 扭曲','["contort"]','["Contort the meaning."]','["con","tort"]'),
('w_0579','retort','/rɪˈtɔːt/','verb','v. 反驳','["retort"]','["Retort with anger."]','["re","tort"]'),
('w_0580','torch','/tɔːtʃ/','noun','n. 火炬','["torch"]','["Olympic torch."]','["tord"]'),
('w_0581','torment','/ˈtɔːment/','noun','n. 折磨','["torment"]','["Emotional torment."]','["tor"]'),
('w_0582','tornado','/tɔːˈneɪdəʊ/','noun','n. 龙卷风','["tornado"]','["Destroyed by tornado."]','["torn"]'),
('w_0583','attorney','/əˈtɜːni/','noun','n. 代理人','["attorney"]','["Power of attorney."]','["at"]'),
('w_0584','conform','/kənˈfɔːm/','verb','v. 符合','["conform"]','["Conform to standards."]','["con","form"]'),
('w_0585','deform','/dɪˈfɔːm/','verb','v. 变形','["deform"]','["Metals deform under pressure."]','["de","form"]'),
('w_0586','inform','/ɪnˈfɔːm/','verb','v. 通知','["inform"]','["Inform employees."]','["in","form"]'),
('w_0587','reform','/rɪˈfɔːm/','verb','v. 改革','["reform"]','["Reform the system."]','["re","form"]'),
('w_0588','transform','/trænsˈfɔːm/','verb','v. 改变','["transform"]','["Transform the economy."]','["trans","form"]'),
('w_0589','formula','/ˈfɔːmjʊlə/','noun','n. 公式','["formula"]','["Mathematical formula."]','["form"]'),
('w_0590','formulate','/ˈfɔːmjʊleɪt/','verb','v. 制定','["formulate"]','["Formulate a plan."]','["form"]'),
('w_0591','perform','/pəˈfɔːm/','verb','v. 执行','["perform"]','["Perform a task."]','["per","form"]'),
('w_0592','performance','/pəˈfɔːməns/','noun','n. 性能','["performance"]','["High performance."]','["per","form"]'),
('w_0593','uniform','/ˈjuːnɪfɔːm/','noun','n. 制服','["uniform"]','["School uniform."]','["uni","form"]'),
('w_0594','platform','/ˈplætfɔːm/','noun','n. 平台','["platform"]','["Social platform."]','["plat","form"]'),
('w_0595','multiform','/ˈmʌltɪfɔːm/','adj','adj. 多形的','["multiform"]','["Multiform expressions."]','["multi","form"]'),
('w_0596','convention','/kənˈvenʃən/','noun','n. 惯例','["convention"]','["Social convention."]','["con","vent"]'),
('w_0597','conventional','/kənˈvenʃənəl/','adj','adj. 传统的','["conventional"]','["Conventional methods."]','["con","vent"]'),
('w_0598','invent','/ɪnˈvent/','verb','v. 发明','["invent"]','["Invent a device."]','["in","vent"]'),
('w_0599','prevent','/prɪˈvent/','verb','v. 预防','["prevent"]','["Prevent accidents."]','["pre","vent"]'),
('w_0600','event','/ɪˈvent/','noun','n. 事件','["event"]','["Special event."]','["e","vent"]');
