-- 清空并插入65个核心词汇
DELETE FROM words;

INSERT INTO words (word_id, word, phonetic, pos, definition, family, examples, roots) VALUES
('w_0001','beneficiary','/ˌbenɪˈfɪʃəri/','noun','n. 受益人','["benefit","beneficial"]','["The beneficiary received payments."]','["bene"]'),
('w_0002','benefit','/ˈbenɪfɪt/','noun','n. 利益，好处','["beneficial"]','["Regular exercise has many benefits."]','["bene","fit"]'),
('w_0003','benevolent','/bɪˈnevələnt/','adj','adj. 仁慈的','["benediction"]','["A benevolent smile."]','["bene","vol"]'),
('w_0004','benign','/bɪˈnaɪn/','adj','adj. 良性的','[]','["The tumor was benign."]','["bene"]'),
('w_0005','benediction','/ˌbenɪˈdɪkʃən/','noun','n. 祝福','[]','["The priest gave the benediction."]','["bene","dict"]'),
('w_0006','malice','/ˈmælɪs/','noun','n. 恶意','["malicious","malign"]','["He bore no malice."]','["mal"]'),
('w_0007','malicious','/məˈlɪʃəs/','adj','adj. 恶意的','["malice"]','["Malicious software."]','["mal"]'),
('w_0008','malign','/məˈlaɪn/','adj','adj. 恶性的','["malignant"]','["Malign influence."]','["mal"]'),
('w_0009','malignant','/məˈlɪɡnənt/','adj','adj. 恶性的','["malign","benign"]','["Malignant tumor."]','["mal"]'),
('w_0010','malnutrition','/ˌmælnjuːˈtrɪʃən/','noun','n. 营养不良','["nutrition"]','["Child malnutrition."]','["mal","nutri"]'),
('w_0011','paradigm','/ˈpærədaɪm/','noun','n. 范式，模式','[]','["A paradigm shift."]','["para","dig"]'),
('w_0012','paradox','/ˈpærədɒks/','noun','n. 悖论','[]','["The paradox of choice."]','["para","dox"]'),
('w_0013','parameter','/pəˈræmɪtər/','noun','n. 参数','[]','["Key parameters."]','["para","meter"]'),
('w_0014','parallel','/ˈpærəlel/','adj','adj. 平行的','[]','["Parallel lines."]','["para","allel"]'),
('w_0015','paralysis','/pəˈræləsɪs/','noun','n. 瘫痪','[]','["Political paralysis."]','["para","lys"]'),
('w_0016','parasite','/ˈpærəsaɪt/','noun','n. 寄生虫','[]','["A social parasite."]','["para","sit"]'),
('w_0017','paragraph','/ˈpærəɡrɑːf/','noun','n. 段落','[]','["Read the first paragraph."]','["para","graph"]'),
('w_0018','spectacular','/spekˈtækjʊlər/','adj','adj. 壮观的','["spectacle"]','["A spectacular view."]','["spect"]'),
('w_0019','spectrum','/ˈspektrəm/','noun','n. 光谱，范围','[]','["Political spectrum."]','["spect"]'),
('w_0020','speculate','/ˈspekjʊleɪt/','verb','v. 推测','[]','["Speculate on the future."]','["spect"]'),
('w_0021','spectator','/spekˈteɪtər/','noun','n. 观众','[]','["The spectators cheered."]','["spect"]'),
('w_0022','respect','/rɪˈspekt/','verb','v. 尊敬','[]','["Respect your elders."]','["re","spect"]'),
('w_0023','inspect','/ɪnˈspekt/','verb','v. 检查','[]','["Inspect the equipment."]','["in","spect"]'),
('w_0024','prospect','/ˈprɒspekt/','noun','n. 前景','[]','["Job prospects."]','["pro","spect"]'),
('w_0025','retrospect','/ˈretrəspekt/','noun','n. 回顾','[]','["In retrospect."]','["retro","spect"]'),
('w_0026','describe','/dɪˈskraɪb/','verb','v. 描述','[]','["Describe what happened."]','["de","scribe"]'),
('w_0027','prescribe','/prɪˈskraɪb/','verb','v. 开处方','[]','["The doctor prescribed medication."]','["pre","scribe"]'),
('w_0028','subscribe','/səbˈskraɪb/','verb','v. 订阅','[]','["Subscribe to the magazine."]','["sub","scribe"]'),
('w_0029','manuscript','/ˈmænjʊskrɪpt/','noun','n. 手稿','[]','["Ancient manuscripts."]','["manu","script"]'),
('w_0030','inscribe','/ɪnˈskraɪb/','verb','v. 题写','[]','["Inscribe the book."]','["in","scribe"]'),
('w_0031','dictate','/dɪkˈteɪt/','verb','v. 口述','[]','["Dictate a letter."]','["dict"]'),
('w_0032','predict','/prɪˈdɪkt/','verb','v. 预言','[]','["Predict the weather."]','["pre","dict"]'),
('w_0033','contradict','/ˌkɒntrəˈdɪkt/','verb','v. 反驳','[]','["Do not contradict me."]','["contra","dict"]'),
('w_0034','indicate','/ˈɪndɪkeɪt/','verb','v. 表明','[]','["Indicate your choice."]','["in","dic"]'),
('w_0035','dedicate','/ˈdedɪkeɪt/','verb','v. 奉献','[]','["Dedicate his life to science."]','["de","dic"]'),
('w_0036','jurisdiction','/ˌdʒʊərɪsˈdɪkʃən/','noun','n. 司法权','[]','["Federal jurisdiction."]','["juris","dict"]'),
('w_0037','conduct','/kənˈdʌkt/','verb','v. 执行','[]','["Conduct an experiment."]','["con","duct"]'),
('w_0038','deduce','/dɪˈdjuːs/','verb','v. 推论','[]','["Deduce the answer."]','["de","duc"]'),
('w_0039','induce','/ɪnˈdjuːs/','verb','v. 诱导','[]','["Induce vomiting."]','["in","duc"]'),
('w_0040','produce','/prəˈdjuːs/','verb','v. 生产','[]','["Produce goods."]','["pro","duc"]'),
('w_0041','reduce','/rɪˈdjuːs/','verb','v. 减少','[]','["Reduce costs."]','["re","duc"]'),
('w_0042','reproduce','/ˌriːprəˈdjuːs/','verb','v. 繁殖','[]','["Reproduce the data."]','["re","pro","duc"]'),
('w_0043','introduce','/ˌɪntrəˈdjuːs/','verb','v. 介绍','[]','["Introduce yourself."]','["intro","duc"]'),
('w_0044','compel','/kəmˈpel/','verb','v. 强迫','[]','["Compel obedience."]','["com","pel"]'),
('w_0045','expel','/ɪkˈspel/','verb','v. 驱逐','[]','["Expel from school."]','["ex","pel"]'),
('w_0046','propel','/prəˈpel/','verb','v. 推进','[]','["Propel the boat."]','["pro","pel"]'),
('w_0047','repel','/rɪˈpel/','verb','v. 击退','[]','["Repel the enemy."]','["re","pel"]'),
('w_0048','venture','/ˈventʃər/','noun','n. 风险项目','[]','["A joint venture."]','["vent"]'),
('w_0049','adventure','/ədˈventʃər/','noun','n. 冒险','[]','["Life is an adventure."]','["ad","vent"]'),
('w_0050','convention','/kənˈvenʃən/','noun','n. 惯例','[]','["International convention."]','["con","ven"]'),
('w_0051','convene','/kənˈviːn/','verb','v. 召集','[]','["The meeting will convene."]','["con","ven"]'),
('w_0052','prevent','/prɪˈvent/','verb','v. 阻止','[]','["Prevent accidents."]','["pre","vent"]'),
('w_0053','intervene','/ˌɪntəˈviːn/','verb','v. 干涉','[]','["Intervene in the conflict."]','["inter","ven"]'),
('w_0054','revenue','/ˈrevənjuː/','noun','n. 收入','[]','["Annual revenue."]','["re","ven"]'),
('w_0055','avenue','/ˈævənjuː/','noun','n. 大街','[]','["Fifth Avenue."]','["a","ven"]'),
('w_0056','circumvent','/ˌsɜːkəmˈvent/','verb','v. 绕过','[]','["Circumvent the rules."]','["circum","vent"]'),
('w_0057','evidence','/ˈevɪdəns/','noun','n. 证据','[]','["Scientific evidence."]','["e","vid"]'),
('w_0058','evident','/ˈevɪdənt/','adj','adj. 明显的','[]','["It is evident."]','["e","vid"]'),
('w_0059','provide','/prəˈvaɪd/','verb','v. 提供','[]','["Provide support."]','["pro","vid"]'),
('w_0060','visible','/ˈvɪzəbl/','adj','adj. 可见的','[]','["Not visible."]','["vis"]'),
('w_0061','vision','/ˈvɪʒən/','noun','n. 视野','[]','["A clear vision."]','["vis"]'),
('w_0062','revise','/rɪˈvaɪz/','verb','v. 修订','[]','["Revise the manuscript."]','["re","vis"]'),
('w_0063','supervise','/ˈsuːpəvaɪz/','verb','v. 监督','[]','["Supervise the project."]','["super","vis"]'),
('w_0064','advise','/ədˈvaɪz/','verb','v. 建议','[]','["I advise you."]','["ad","vis"]'),
('w_0065','television','/ˈtelɪvɪʒən/','noun','n. 电视','[]','["Watch television."]','["tele","vis"]');

SELECT COUNT(*) as total FROM words;
