-- 添加词汇 601-700
INSERT INTO words (word_id, word, phonetic, pos, definition, family, examples, roots) VALUES
('w_0601','adventure','/ədˈventʃər/','noun','n. 冒险','["adventure"]','["Exciting adventure."]','["ad","vent"]'),
('w_0602','ventilate','/ˈventɪleɪt/','verb','v. 通风','["ventilate"]','["Ventilate the room."]','["vent"]'),
('w_0603','convene','/kənˈviːn/','verb','v. 召集','["convene"]','["Convene a meeting."]','["con","ven"]'),
('w_0604','intervene','/ˌɪntəˈviːn/','verb','v. 干预','["intervene"]','["Intervene in crisis."]','["inter","ven"]'),
('w_0605','revenue','/ˈrevənjuː/','noun','n. 收入','["revenue"]','["Annual revenue."]','["re","ven"]'),
('w_0606','avenue','/ˈævənjuː/','noun','n. 林荫道','["avenue"]','["Fifth Avenue."]','["a","ven"]'),
('w_0607','circumvent','/ˌsɜːkəmˈvent/','verb','v. 规避','["circumvent"]','["Circumvent rules."]','["circum","vent"]'),
('w_0608','eventual','/ɪˈventʃʊəl/','adj','adj. 最终的','["eventual"]','["Eventual success."]','["event"]'),
('w_0609','intervene','/ˌɪntəˈviːn/','verb','v. 进入','["intervene"]','["Time will intervene."]','["inter"]'),
('w_0610','convention','/kənˈvenʃən/','noun','n. 会议','["convention"]','["National convention."]','["con"]'),
('w_0611','verbal','/ˈvɜːbəl/','adj','adj. 口头的','["verbal"]','["Verbal communication."]','["verb"]'),
('w_0612','proverb','/ˈprɒvɜːb/','noun','n. 谚语','["proverb"]','["Chinese proverb."]','["pro","verb"]'),
('w_0613','verbose','/vɜːˈbəʊs/','adj','adj. 冗长的','["verbose"]','["Verbose writing."]','["verb"]'),
('w_0614','adverb','/ˈædvɜːb/','noun','n. 副词','["adverb"]','["Grammar: adverb."]','["ad","verb"]'),
('w_0615','verbatim','/vɜːˈbeɪtɪm/','adj','adj. 逐字的','["verbatim"]','["Verbatim report."]','["verb"]'),
('w_0616','verbalize','/ˈvɜːbəlaɪz/','verb','v. 用言语表达','["verbalize"]','["Verbalize thoughts."]','["verb"]'),
('w_0617','verify','/ˈverɪfaɪ/','verb','v. 核实','["verify"]','["Verify information."]','["ver","ify"]'),
('w_0618','versatile','/ˈvɜːsətaɪl/','adj','adj. 多功能的','["versatile"]','["Versatile skill."]','["vers"]'),
('w_0619','version','/ˈvɜːʃən/','noun','n. 版本','["version"]','["Latest version."]','["vers"]'),
('w_0620','versus','/ˈvɜːsəs/','prep','prep. 对比','["versus"]','["China versus Japan."]','["vers"]'),
('w_0621','verse','/vɜːs/','noun','n. 诗句','["verse"]','["Poetic verse."]','["vers"]'),
('w_0622','reversal','/rɪˈvɜːsəl/','noun','n. 逆转','["reversal"]','["Policy reversal."]','["re","vers"]'),
('w_0623','diverse','/daɪˈvɜːs/','adj','adj. 多样的','["diverse"]','["Diverse opinions."]','["di","vers"]'),
('w_0624','diversify','/daɪˈvɜːsɪfaɪ/','verb','v. 使多样化','["diversify"]','["Diversify investments."]','["di","vers"]'),
('w_0625','advertise','/ˈædvətaɪz/','verb','v. 做广告','["advertise"]','["Advertise products."]','["ad","vert"]'),
('w_0626','advertisement','/ədˈvɜːtɪsmənt/','noun','n. 广告','["advertisement"]','["TV advertisement."]','["ad","vert"]'),
('w_0627','convert','/kənˈvɜːt/','verb','v. 转换','["convert"]','["Convert currency."]','["con","vert"]'),
('w_0628','invert','/ɪnˈvɜːt/','verb','v. 颠倒','["invert"]','["Invert the image."]','["in","vert"]'),
('w_0629','pervert','/pəˈvɜːt/','verb','v. 曲解','["pervert"]','["Pervert justice."]','["per","vert"]'),
('w_0630','revert','/rɪˈvɜːt/','verb','v. 恢复','["revert"]','["Revert to old ways."]','["re","vert"]'),
('w_0631','divert','/daɪˈvɜːt/','verb','v. 转移','["divert"]','["Divert attention."]','["di","vert"]'),
('w_0632','aversion','/əˈvɜːʃən/','noun','n. 厌恶','["aversion"]','["Have an aversion to."]','["a","vers"]'),
('w_0633','adverse','/ˈædvɜːs/','adj','adj. 不利的','["adverse"]','["Adverse conditions."]','["ad","vers"]'),
('w_0634','adversary','/ˈædvəsəri/','noun','n. 对手','["adversary"]','["Political adversary."]','["ad","vers"]'),
('w_0635','anniversary','/ˌænɪˈvɜːsəri/','noun','n. 周年纪念','["anniversary"]','["Wedding anniversary."]','["annus","vers"]'),
('w_0636','universe','/ˈjuːnɪvɜːs/','noun','n. 宇宙','["universe"]','["The universe."]','["uni","vers"]'),
('w_0637','university','/ˌjuːnɪˈvɜːsɪti/','noun','n. 大学','["university"]','["State university."]','["uni","vers"]'),
('w_0638','vertical','/ˈvɜːtɪkəl/','adj','adj. 垂直的','["vertical"]','["Vertical line."]','["vert"]'),
('w_0639','vertigo','/ˈvɜːtɪɡəʊ/','noun','n. 眩晕','["vertigo"]','["Feel vertigo."]','["vert"]'),
('w_0640','avert','/əˈvɜːt/','verb','v. 避免','["avert"]','["Avert crisis."]','["a","vert"]'),
('w_0641','vision','/ˈvɪʒən/','noun','n. 视力','["vision"]','["Poor vision."]','["vis"]'),
('w_0642','visible','/ˈvɪzɪbl/','adj','adj. 可见的','["visible"]','["Visible stars."]','["vis"]'),
('w_0643','revise','/rɪˈvaɪz/','verb','v. 修订','["revise"]','["Revise documents."]','["re","vis"]'),
('w_0644','supervise','/ˈsuːpəvaɪz/','verb','v. 监督','["supervise"]','["Supervise workers."]','["super","vis"]'),
('w_0645','adviser','/ədˈvaɪzər/','noun','n. 顾问','["adviser"]','["Financial adviser."]','["ad","vis"]'),
('w_0646','envisage','/ɪnˈvɪzɪdʒ/','verb','v. 设想','["envisage"]','["Envisage the future."]','["en","vis"]'),
('w_0647','provision','/prəˈvɪʒən/','noun','n. 供应','["provision"]','["Food provision."]','["pro","vis"]'),
('w_0648','ivision','/dɪˈvɪʒən/','noun','n. 分开','["division"]','["Cell division."]','["di","vis"]'),
('w_0649','devise','/dɪˈvaɪz/','verb','v. 设计','["devise"]','["Devise a plan."]','["de","vis"]'),
('w_0650','television','/ˈtelɪvɪʒən/','noun','n. 电视','["television"]','["Watch television."]','["tele","vis"]'),
('w_0651','visual','/ˈvɪʒʊəl/','adj','adj. 视觉的','["visual"]','["Visual arts."]','["vis"]'),
('w_0652','visualize','/ˈvɪʒʊəlaɪz/','verb','v. 可视化','["visualize"]','["Visualize data."]','["vis"]'),
('w_0653','envision','/ɪnˈvɪʒən/','verb','v. 想象','["envision"]','["Envision success."]','["en","vis"]'),
('w_0654','provisional','/prəˈvɪʒənəl/','adj','adj. 临时的','["provisional"]','["Provisional government."]','["pro","vis"]'),
('w_0655','visit','/ˈvɪzɪt/','verb','v. 访问','["visit"]','["Visit website."]','["vis"]'),
('w_0656','visitor','/ˈvɪzɪtər/','noun','n. 访客','["visitor"]','["Website visitors."]','["vis"]'),
('w_0657','visa','/ˈviːzə/','noun','n. 签证','["visa"]','["Tourist visa."]','["vis"]'),
('w_0658','prudent','/ˈpruːdənt/','adj','adj. 谨慎的','["prudent"]','["Prudent decision."]','["pru","den"]'),
('w_0659','prudence','/ˈpruːdəns/','noun','n. 谨慎','["prudence"]','["Financial prudence."]','["pru","den"]'),
('w_0660','imprudent','/ɪmˈpruːdənt/','adj','adj. 轻率的','["imprudent"]','["Imprudent behavior."]','["im","pru"]'),
('w_0661','denounce','/dɪˈnaʊns/','verb','v. 谴责','["denounce"]','["Denounce corruption."]','["de","nounce"]'),
('w_0662','announce','/əˈnaʊns/','verb','v. 宣布','["announce"]','["Announce results."]','["an","nounce"]'),
('w_0663','pronounce','/prəˈnaʊns/','verb','v. 发音','["pronounce"]','["Pronounce correctly."]','["pro","nounce"]'),
('w_0664','renounce','/rɪˈnaʊns/','verb','v. 放弃','["renounce"]','["Renounce citizenship."]','["re","nounce"]'),
('w_0665','denounce','/dɪˈnaʊns/','verb','v. 告发','["denounce"]','["Denounce criminals."]','["de"]'),
('w_0666','nounce','/naʊns/','noun','n. 呼唤','["nounce"]','["Announce clearly."]','["nounce"]'),
('w_0667','notorious','/nəʊˈtɔːriəs/','adj','adj. 臭名昭著的','["notorious"]','["Notorious criminal."]','["not"]'),
('w_0668','notice','/ˈnəʊtɪs/','verb','v. 注意','["notice"]','["Notice changes."]','["not"]'),
('w_0669','notable','/ˈnəʊtəbl/','adj','adj. 值得注意的','["notable"]','["Notable achievement."]','["not"]'),
('w_0670','notation','/nəʊˈteɪʃən/','noun','n. 记号','["notation"]','["Musical notation."]','["not"]'),
('w_0671','annotate','/ˈænəteɪt/','verb','v. 注解','["annotate"]','["Annotate texts."]','["an","not"]'),
('w_0672','notion','/ˈnəʊʃən/','noun','n. 概念','["notion"]','["Basic notions."]','["not"]'),
('w_0673','notify','/ˈnəʊtɪfaɪ/','verb','v. 通知','["notify"]','["Notify users."]','["not","ify"]'),
('w_0674','notoriety','/ˌnəʊtəˈraɪəti/','noun','n. 恶名','["notoriety"]','["Gain notoriety."]','["not"]'),
('w_0675','notwithstanding','/ˌnɒtwɪðˈstændɪŋ/','prep','prep. 尽管','["notwithstanding"]','["Notwithstanding the difficulty."]','["not","stand"]'),
('w_0676','notify','/ˈnəʊtɪfaɪ/','verb','v. 公布','["notify"]','["Public notify."]','["not"]'),
('w_0677','notch','/nɒtʃ/','noun','n. 刻痕','["notch"]','["Cut a notch."]','["notch"]'),
('w_0678','notch','/nɒtʃ/','verb','v. 刻痕','["notch"]','["Notch the surface."]','["notch"]'),
('w_0679','inaugurate','/ɪˈnɔːɡjʊreɪt/','verb','v. 开始','["inaugurate"]','["Inaugurate a new era."]','["in","aug"]'),
('w_0680','augment','/ɔːɡˈment/','verb','v. 增加','["augment"]','["Augment income."]','["aug"]'),
('w_0681','august','/ɔːˈɡʌst/','adj','adj. 威严的','["august"]','["August presence."]','["aug"]'),
('w_0682','auxiliary','/ɔːɡˈzɪlɪəri/','adj','adj. 辅助的','["auxiliary"]','["Auxiliary equipment."]','["aux"]'),
('w_0683','author','/ˈɔːθər/','noun','n. 作者','["author"]','["Book author."]','["auth"]'),
('w_0684','authority','/ɔːˈθɒrɪti/','noun','n. 权威','["authority"]','["Government authority."]','["auth"]'),
('w_0685','authorize','/ˈɔːθəraɪz/','verb','v. 授权','["authorize"]','["Authorize payment."]','["auth"]'),
('w_0686','authentic','/ɔːˈθentɪk/','adj','adj. 真实的','["authentic"]','["Authentic document."]','["auth"]'),
('w_0687','authenticate','/ɔːˈθentɪkeɪt/','verb','v. 认证','["authenticate"]','["Authenticate identity."]','["auth"]'),
('w_0688','autobiography','/ˌɔːtəbaɪˈɒɡrəfi/','noun','n. 自传','["autobiography"]','["Write autobiography."]','["auto","bio"]'),
('w_0689','autonomy','/ɔːˈtɒnəmi/','noun','n. 自治','["autonomy"]','["Regional autonomy."]','["auto","nom"]'),
('w_0690','automatic','/ˌɔːtəˈmætɪk/','adj','adj. 自动的','["automatic"]','["Automatic door."]','["auto","mat"]'),
('w_0691','automate','/ˈɔːtəmeɪt/','verb','v. 自动化','["automate"]','["Automate production."]','["auto","mat"]'),
('w_0692','autonomous','/ɔːˈtɒnəməs/','adj','adj. 自主的','["autonomous"]','["Autonomous vehicle."]','["auto","nom"]'),
('w_0693','autopsy','/ˈɔːtɒpsi/','noun','n. 验尸','["autopsy"]','["Forensic autopsy."]','["auto","psy"]'),
('w_0694','benefit','/ˈbenɪfɪt/','noun','n. 利益','["benefit"]','["Health benefit."]','["bene","fit"]'),
('w_0695','beneficial','/ˌbenɪˈfɪʃəl/','adj','adj. 有益的','["beneficial"]','["Beneficial effects."]','["bene","fic"]'),
('w_0696','beneficiary','/ˌbenɪˈfɪʃəri/','noun','n. 受益人','["beneficiary"]','["Insurance beneficiary."]','["bene","fic"]'),
('w_0697','benevolent','/bɪˈnevələnt/','adj','adj. 仁慈的','["benevolent"]','["Benevolent leader."]','["bene","vol"]'),
('w_0698','benign','/bɪˈnaɪn/','adj','adj. 良性的','["benign"]','["Benign tumor."]','["bene"]'),
('w_0699','benediction','/ˌbenɪˈdɪkʃən/','noun','n. 祝福','["benediction"]','["Church benediction."]','["bene","dict"]'),
('w_0700','beneficence','/bɪˈnefɪsəns/','noun','n. 善行','["beneficence"]','["Act of beneficence."]','["bene","fic"]');
