-- 添加词汇 66-200
INSERT INTO words (word_id, word, phonetic, pos, definition, family, examples, roots) VALUES
('w_0066','concise','/kənˈsaɪs/','adj','adj. 简明的','[]','["A concise summary."]','["con","cise"]'),
('w_0067','precise','/prɪˈsaɪs/','adj','adj. 精确的','["precision"]','["Precise measurements."]','["pre","cise"]'),
('w_0068','decision','/dɪˈsɪʒən/','noun','n. 决定','["decide"]','["Make a decision."]','["de","cis"]'),
('w_0069','attract','/əˈtrækt/','verb','v. 吸引','["attraction"]','["Attract attention."]','["at","tract"]'),
('w_0070','contract','/ˈkɒntrækt/','noun','n. 合同','[]','["Sign a contract."]','["con","tract"]'),
('w_0071','extract','/ˈekstrækt/','verb','v. 提取','[]','["Extract information."]','["ex","tract"]'),
('w_0072','distract','/dɪˈstrækt/','verb','v. 使分心','[]','["Distract from work."]','["dis","tract"]'),
('w_0073','subtract','/səbˈtrækt/','verb','v. 减去','[]','["Subtract the cost."]','["sub","tract"]'),
('w_0074','convert','/kənˈvɜːt/','verb','v. 转换','["conversion"]','["Convert dollars."]','["con","vert"]'),
('w_0075','revert','/rɪˈvɜːt/','verb','v. 恢复','[]','["Revert to old habits."]','["re","vert"]'),
('w_0076','divert','/daɪˈvɜːt/','verb','v. 使转向','[]','["Divert traffic."]','["di","vert"]'),
('w_0077','adverse','/ˈædvɜːs/','adj','adj. 不利的','[]','["Adverse conditions."]','["ad","verse"]'),
('w_0078','reverse','/rɪˈvɜːs/','verb','v. 颠倒','[]','["Reverse the order."]','["re","verse"]'),
('w_0079','diverse','/daɪˈvɜːs/','adj','adj. 多样的','["diversity"]','["Diverse opinions."]','["di","verse"]'),
('w_0080','universe','/ˈjuːnɪvɜːs/','noun','n. 宇宙','[]','["The entire universe."]','["uni","verse"]'),
('w_0081','compose','/kəmˈpəʊz/','verb','v. 组成','[]','["Compose music."]','["com","pose"]'),
('w_0082','oppose','/əˈpəʊz/','verb','v. 反对','["opposition"]','["Oppose the plan."]','["op","pose"]'),
('w_0083','propose','/prəˈpəʊz/','verb','v. 提议','["proposal"]','["Propose a solution."]','["pro","pose"]'),
('w_0084','suppose','/səˈpəʊz/','verb','v. 假设','[]','["I suppose so."]','["sup","pose"]'),
('w_0085','expose','/ɪkˈspəʊz/','verb','v. 暴露','[]','["Expose to light."]','["ex","pose"]'),
('w_0086','impose','/ɪmˈpəʊz/','verb','v. 强制推行','[]','["Impose rules."]','["im","pose"]'),
('w_0087','dispose','/dɪˈspəʊz/','verb','v. 处理','["disposal"]','["Dispose of waste."]','["dis","pose"]'),
('w_0088','construct','/kənˈstrʌkt/','verb','v. 建造','["construction"]','["Construct a building."]','["con","struct"]'),
('w_0089','destruction','/dɪˈstrʌkʃən/','noun','n. 破坏','["destroy"]','["Environmental destruction."]','["de","struct"]'),
('w_0090','instruct','/ɪnˈstrʌkt/','verb','v. 指导','["instruction"]','["Instruct students."]','["in","struct"]'),
('w_0091','obstruct','/əbˈstrʌkt/','verb','v. 阻碍','[]','["Obstruct the view."]','["ob","struct"]'),
('w_0092','compress','/kəmˈpres/','verb','v. 压缩','[]','["Compress the file."]','["com","press"]'),
('w_0093','depress','/dɪˈpres/','verb','v. 使沮丧','["depression"]','["Depress the economy."]','["de","press"]'),
('w_0094','express','/ɪkˈspres/','verb','v. 表达','["expression"]','["Express your feelings."]','["ex","press"]'),
('w_0095','impress','/ɪmˈpres/','verb','v. 留下印象','["impression"]','["Impress the interviewer."]','["im","press"]'),
('w_0096','transmit','/trænzˈmɪt/','verb','v. 传输','["transmission"]','["Transmit data."]','["trans","mit"]'),
('w_0097','emit','/ɪˈmɪt/','verb','v. 发出','[]','["Emit light."]','["e","mit"]'),
('w_0098','submit','/səbˈmɪt/','verb','v. 提交','[]','["Submit the report."]','["sub","mit"]'),
('w_0099','permit','/pəˈmɪt/','verb','v. 允许','[]','["Permit entry."]','["per","mit"]'),
('w_0100','omit','/əˈmɪt/','verb','v. 省略','[]','["Omit the details."]','["o","mit"]');
