-- 添加词汇 101-200
INSERT INTO words (word_id, word, phonetic, pos, definition, family, examples, roots) VALUES
('w_0101','commit','/kəˈmɪt/','verb','v. 承诺','[]','["Commit a crime."]','["com","mit"]'),
('w_0102','extend','/ɪkˈstend/','verb','v. 扩展','[]','["Extend the deadline."]','["ex","tend"]'),
('w_0103','intend','/ɪnˈtend/','verb','v. 打算','[]','["I intend to go."]','["in","tend"]'),
('w_0104','pretend','/prɪˈtend/','verb','v. 假装','[]','["Pretend to be happy."]','["pre","tend"]'),
('w_0105','attend','/əˈtend/','verb','v. 参加','[]','["Attend the meeting."]','["at","tend"]'),
('w_0106','contend','/kənˈtend/','verb','v. 竞争','[]','["Contend for the prize."]','["con","tend"]'),
('w_0107','invade','/ɪnˈveɪd/','verb','v. 入侵','[]','["Invade the country."]','["in","vade"]'),
('w_0108','evade','/ɪˈveɪd/','verb','v. 逃避','[]','["Evade taxes."]','["e","vade"]'),
('w_0109','pervade','/pəˈveɪd/','verb','v. 弥漫','[]','["Pervade the market."]','["per","vade"]'),
('w_0110','confuse','/kənˈfjuːz/','verb','v. 使困惑','[]','["Confuse the enemy."]','["con","fuse"]'),
('w_0111','refuse','/rɪˈfjuːz/','verb','v. 拒绝','[]','["Refuse the offer."]','["re","fuse"]'),
('w_0112','diffuse','/dɪˈfjuːs/','verb','v. 扩散','[]','["Diffuse light."]','["dis","fuse"]'),
('w_0113','infuse','/ɪnˈfjuːz/','verb','v. 注入','[]','["Infuse new life."]','["in","fuse"]'),
('w_0114','claim','/kleɪm/','verb','v. 声称','[]','["Claim responsibility."]','["claim"]'),
('w_0115','exclaim','/ɪkˈskleɪm/','verb','v. 呼喊','[]','["Exclaim in surprise."]','["ex","claim"]'),
('w_0116','proclaim','/prəˈkleɪm/','verb','v. 宣布','[]','["Proclaim the result."]','["pro","claim"]'),
('w_0117','reclaim','/rɪˈkleɪm/','verb','v. 回收','[]','["Reclaim land."]','["re","claim"]'),
('w_0118','suspend','/səsˈpend/','verb','v. 暂停','[]','["Suspend the game."]','["sus","pend"]'),
('w_0119','expend','/ɪkˈspend/','verb','v. 花费','[]','["Expend energy."]','["ex","pend"]'),
('w_0120','depend','/dɪˈpend/','verb','v. 依赖','[]','["Depend on others."]','["de","pend"]'),
('w_0121','independent','/ˌɪndɪˈpendənt/','adj','adj. 独立的','[]','["Independent thinking."]','["in","de","pend"]'),
('w_0122','append','/əˈpend/','verb','v. 附加','[]','["Append a signature."]','["ap","pend"]'),
('w_0123','confess','/kənˈfes/','verb','v. 承认','[]','["Confess the truth."]','["con","fess"]'),
('w_0124','profess','/prəˈfes/','verb','v. 声称','[]','["Profess his love."]','["pro","fess"]'),
('w_0125','formulate','/ˈfɔːmjʊleɪt/','verb','v. 制定','[]','["Formulate a plan."]','["form"]'),
('w_0126','transform','/trænsˈfɔːm/','verb','v. 改变','[]','["Transform the system."]','["trans","form"]'),
('w_0127','reform','/rɪˈfɔːm/','verb','v. 改革','[]','["Reform the policy."]','["re","form"]'),
('w_0128','conform','/kənˈfɔːm/','verb','v. 遵守','[]','["Conform to the rules."]','["con","form"]'),
('w_0129','uniform','/ˈjuːnɪfɔːm/','noun','n. 制服','[]','["School uniform."]','["uni","form"]'),
('w_0130','perform','/pəˈfɔːm/','verb','v. 执行','[]','["Perform on stage."]','["per","form"]'),
('w_0131','bankrupt','/ˈbæŋkrʌpt/','adj','adj. 破产的','[]','["Go bankrupt."]','["bank","rupt"]'),
('w_0132','corrupt','/kəˈrʌpt/','adj','adj. 腐败的','[]','["Corrupt officials."]','["cor","rupt"]'),
('w_0133','erupt','/ɪˈrʌpt/','verb','v. 爆发','[]','["Volcano erupts."]','["e","rupt"]'),
('w_0134','interrupt','/ˌɪntəˈrʌpt/','verb','v. 中断','[]','["Do not interrupt."]','["inter","rupt"]'),
('w_0135','disrupt','/dɪsˈrʌpt/','verb','v. 扰乱','[]','["Disrupt the market."]','["dis","rupt"]'),
('w_0136','conclude','/kənˈkluːd/','verb','v. 结束','[]','["Conclude the meeting."]','["con","clude"]'),
('w_0137','exclude','/ɪkˈskluːd/','verb','v. 排除','[]','["Exclude the possibility."]','["ex","clude"]'),
('w_0138','include','/ɪnˈkluːd/','verb','v. 包含','[]','["Include all items."]','["in","clude"]'),
('w_0139','seclude','/sɪˈkluːd/','verb','v. 隔离','[]','["Seclude oneself."]','["se","clude"]'),
('w_0140','forecast','/ˈfɔːkɑːst/','noun','n. 预测','[]','["Weather forecast."]','["fore","cast"]'),
('w_0141','foresee','/fɔːˈsiː/','verb','v. 预见','[]','["Foresee the future."]','["fore","see"]'),
('w_0142','interact','/ˌɪntəˈækt/','verb','v. 互动','[]','["Interact with others."]','["inter","act"]'),
('w_0143','interfere','/ˌɪntəˈfɪər/','verb','v. 干涉','[]','["Do not interfere."]','["inter","fere"]'),
('w_0144','interpret','/ɪnˈtɜːprɪt/','verb','v. 解释','[]','["Interpret the meaning."]','["inter","pret"]'),
('w_0145','predict','/prɪˈdɪkt/','verb','v. 预言','[]','["Predict the future."]','["pre","dict"]'),
('w_0146','prepare','/prɪˈpeər/','verb','v. 准备','[]','["Prepare for exam."]','["pre","pare"]'),
('w_0147','preview','/ˈpriːvjuː/','verb','v. 预览','[]','["Preview the document."]','["pre","view"]'),
('w_0148','prevail','/prɪˈveɪl/','verb','v. 流行','[]','["Truth will prevail."]','["pre","vail"]'),
('w_0149','precede','/prɪˈsiːd/','verb','v. 先于','[]','["Winter precedes spring."]','["pre","cede"]'),
('w_0150','superficial','/ˌsuːpəˈfɪʃəl/','adj','adj. 表面的','[]','["Superficial knowledge."]','["super","fic"]'),
('w_0151','supreme','/suːˈpriːm/','adj','adj. 最高的','[]','["Supreme court."]','["supre"]'),
('w_0152','superb','/suːˈpɜːb/','adj','adj. 极好的','[]','["A superb view."]','["super"]'),
('w_0153','transplant','/trænsˈplɑːnt/','verb','v. 移植','[]','["Transplant the tree."]','["trans","plant"]'),
('w_0154','transport','/trænsˈpɔːt/','verb','v. 运输','[]','["Transport goods."]','["trans","port"]'),
('w_0155','transparent','/trænsˈpærənt/','adj','adj. 透明的','[]','["Transparent glass."]','["trans","par"]'),
('w_0156','foreign','/ˈfɒrɪn/','adj','adj. 外国的','[]','["Foreign language."]','["for"]'),
('w_0157','forest','/ˈfɒrɪst/','noun','n. 森林','[]','["Dense forest."]','["fore"]'),
('w_0158','postpone','/pəˈspəʊn/','verb','v. 推迟','[]','["Postpone the meeting."]','["post","pone"]'),
('w_0159','microscope','/ˈmaɪkrəskəʊp/','noun','n. 显微镜','[]','["Look through a microscope."]','["micro","scope"]'),
('w_0160','telephone','/ˈtelɪfəʊn/','noun','n. 电话','[]','["Answer the telephone."]','["tele","phon"]'),
('w_0161','telescope','/ˈtelɪskəʊp/','noun','n. 望远镜','[]','["Astronomical telescope."]','["tele","scop"]'),
('w_0162','television','/ˈtelɪvɪʒən/','noun','n. 电视','[]','["Watch television."]','["tele","vis"]'),
('w_0163','biology','/baɪˈɒlədʒi/','noun','n. 生物学','[]','["Study biology."]','["bio","log"]'),
('w_0164','biography','/baɪˈɒɡrəfi/','noun','n. 传记','[]','["Write a biography."]','["bio","graph"]'),
('w_0165','psychology','/saɪˈkɒlədʒi/','noun','n. 心理学','[]','["Study psychology."]','["psy","ch"]'),
('w_0166','geography','/dʒiˈɒɡrəfi/','noun','n. 地理学','[]','["Study geography."]','["geo","graph"]'),
('w_0167','geology','/dʒiˈɒlədʒi/','noun','n. 地质学','[]','["Study geology."]','["geo","log"]'),
('w_0168','geometry','/dʒiˈɒmɪtri/','noun','n. 几何学','[]','["Learn geometry."]','["geo","meter"]'),
('w_0169','astronomy','/əˈstrɒnəmi/','noun','n. 天文学','[]','["Study astronomy."]','["astro","nom"]'),
('w_0170','automatic','/ˌɔːtəˈmætɪk/','adj','adj. 自动的','[]','["Automatic door."]','["auto","mat"]'),
('w_0171','democracy','/dɪˈmɒkrəsi/','noun','n. 民主','[]','["Western democracy."]','["demo","cracy"]'),
('w_0172','technology','/tekˈnɒlədʒi/','noun','n. 技术','[]','["Advanced technology."]','["tech","log"]'),
('w_0173','photograph','/ˈfəʊtəɡrɑːf/','noun','n. 照片','[]','["Take a photograph."]','["photo","graph"]'),
('w_0174','export','/ɪkˈspɔːt/','verb','v. 出口','[]','["Export goods."]','["ex","port"]'),
('w_0175','import','/ɪmˈpɔːt/','verb','v. 进口','[]','["Import products."]','["im","port"]'),
('w_0176','correct','/kəˈrekt/','adj','adj. 正确的','[]','["Correct answer."]','["cor","rect"]'),
('w_0177','direct','/dɪˈrekt/','verb','v. 指导','[]','["Direct traffic."]','["di","rect"]'),
('w_0178','erect','/ɪˈrekt/','verb','v. 建立','[]','["Erect a building."]','["e","rect"]'),
('w_0179','advice','/ədˈvaɪs/','noun','n. 建议','[]','["Give advice."]','["ad","vis"]'),
('w_0180','visible','/ˈvɪzəbl/','adj','adj. 可见的','[]','["Not visible."]','["vis"]'),
('w_0181','vision','/ˈvɪʒən/','noun','n. 视野','[]','["A clear vision."]','["vis"]'),
('w_0182','revise','/rɪˈvaɪz/','verb','v. 修订','[]','["Revise the manuscript."]','["re","vis"]'),
('w_0183','supervise','/ˈsuːpəvaɪz/','verb','v. 监督','[]','["Supervise the project."]','["super","vis"]'),
('w_0184','advise','/ədˈvaɪz/','verb','v. 建议','[]','["I advise you."]','["ad","vis"]'),
('w_0185','divide','/dɪˈvaɪd/','verb','v. 分开','[]','["Divide the cake."]','["di","vide"]'),
('w_0186','divine','/dɪˈvaɪn/','adj','adj. 神圣的','[]','["Divine power."]','["div"]'),
('w_0187','individual','/ˌɪndɪˈvɪdʒʊəl/','noun','n. 个人','[]','["Rights of individuals."]','["in","di","vid"]'),
('w_0188','provide','/prəˈvaɪd/','verb','v. 提供','[]','["Provide support."]','["pro","vid"]'),
('w_0189','evidence','/ˈevɪdəns/','noun','n. 证据','[]','["Scientific evidence."]','["e","vid"]'),
('w_0190','evident','/ˈevɪdənt/','adj','adj. 明显的','[]','["It is evident."]','["e","vid"]'),
('w_0191','obvious','/ˈɒbvɪəs/','adj','adj. 明显的','[]','["Obvious mistake."]','["ob","vi"]'),
('w_0192','previous','/ˈpriːvɪəs/','adj','adj. 以前的','[]','["Previous experience."]','["pre","vi"]'),
('w_0193','improve','/ɪmˈpruːv/','verb','v. 改进','[]','["Improve skills."]','["im","prov"]'),
('w_0194','approve','/əˈpruːv/','verb','v. 批准','[]','["Approve the plan."]','["ap","prov"]'),
('w_0195','prove','/pruːv/','verb','v. 证明','[]','["Prove innocence."]','["prov"]'),
('w_0196','abstract','/ˈæbstrækt/','adj','adj. 抽象的','[]','["Abstract concept."]','["abs","tract"]'),
('w_0197','attract','/əˈtrækt/','verb','v. 吸引','[]','["Attract attention."]','["at","tract"]'),
('w_0198','contract','/ˈkɒntrækt/','verb','v. 收缩','[]','["Metal contracts."]','["con","tract"]'),
('w_0199','subtract','/səbˈtrækt/','verb','v. 减去','[]','["Subtract the cost."]','["sub","tract"]'),
('w_0200','distract','/dɪˈstrækt/','verb','v. 使分心','[]','["Distract from work."]','["dis","tract"]');
