-- 添加词汇 901-1000
INSERT INTO words (word_id, word, phonetic, pos, definition, family, examples, roots) VALUES
('w_0901','withstand','/wɪðˈstænd/','verb','v. 抵挡','["with","stand"]','["Withstand pressure."]','["with","stand"]'),
('w_0902','withdraw','/wɪðˈdrɔː/','verb','v. 撤回','["with","draw"]','["Withdraw money."]','["with","draw"]'),
('w_0903','withhold','/wɪðˈhəʊld/','verb','v. 扣留','["with","hold"]','["Withhold payment."]','["with","hold"]'),
('w_0904','wither','/ˈwɪðər/','verb','v. 枯萎','["with"]','["Flowers wither."]','["with"]'),
('w_0905','witness','/ˈwɪtnəs/','noun','n. 证人','["wit","ness"]','["Eyewitness."]','["wit","ness"]'),
('w_0906','witty','/ˈwɪti/','adj','adj. 诙谐的','["wit"]','["Witty remark."]','["wit"]'),
('w_0907','witch','/wɪtʃ/','noun','n. 女巫','["wit"]','["Halloween witch."]','["wit"]'),
('w_0908','wretch','/retʃ/','noun','n. 可怜的人','["wretch"]','["Poor wretch."]','["wretch"]'),
('w_0909','wretched','/ˈretʃɪd/','adj','adj. 可怜的','["wretch"]','["Wretched conditions."]','["wretch"]'),
('w_0910','wreck','/rek/','noun','n. 残骸','["wreck"]','["Ship wreck."]','["wreck"]'),
('w_0911','wreckage','/ˈrekɪdʒ/','noun','n. 残骸','["wreck"]','["Aircraft wreckage."]','["wreck"]'),
('w_0912','wrench','/rentʃ/','verb','v. 猛拧','["wrench"]','["Wrench open."]','["wrench"]'),
('w_0913','wrath','/rɒθ/','noun','n. 愤怒','["wrath"]','["God wrath."]','["wrath"]'),
('w_0914','wreath','/riːθ/','noun','n. 花环','["wreath"]','["Christmas wreath."]','["wreath"]'),
('w_0915','wreathe','/riːð/','verb','v. 覆盖','["wreath"]','["Smoke wreathes."]','["wreath"]'),
('w_0916','wrestle','/ˈresl/','verb','v. 摔跤','["wrestl"]','["Wrestle opponent."]','["wrestl"]'),
('w_0917','wrestler','/ˈreslər/','noun','n. 摔跤手','["wrestl"]','["Professional wrestler."]','["wrestl"]'),
('w_0918','wrestling','/ˈreslɪŋ/','noun','n. 摔跤','["wrestl"]','["Olympic wrestling."]','["wrestl"]'),
('w_0919','wriggle','/ˈrɪɡl/','verb','v. 蠕动','["wrigr"]','["Wriggle free."]','["wrigr"]'),
('w_0920','wring','/rɪŋ/','verb','v. 拧','["wr"]','["Wring clothes."]','["wr"]'),
('w_0921','wrinkle','/ˈrɪŋkl/','noun','n. 皱纹','["wrinkl"]','["Face wrinkles."]','["wrinkl"]'),
('w_0922','wrist','/rɪst/','noun','n. 手腕','["wr"]','["Wrist watch."]','["wr"]'),
('w_0923','write','/raɪt/','verb','v. 写','["writ"]','["Write essay."]','["writ"]'),
('w_0924','writer','/ˈraɪtər/','noun','n. 作家','["writ"]','["Professional writer."]','["writ"]'),
('w_0925','writing','/ˈraɪtɪŋ/','noun','n. 写作','["writ"]','["Creative writing."]','["writ"]'),
('w_0926','written','/ˈrɪtən/','adj','adj. 书面的','["writ"]','["Written test."]','["writ"]'),
('w_0927','writhe','/raɪð/','verb','v. 扭曲','["writh"]','["Writhe in pain."]','["writh"]'),
('w_0928','wrong','/rɒŋ/','adj','adj. 错误的','["wrong"]','["Wrong answer."]','["wrong"]'),
('w_0929','wrongful','/ˈrɒŋfʊl/','adj','adj. 不正当的','["wrong"]','["Wrongful arrest."]','["wrong"]'),
('w_0930','wrongly','/ˈrɒŋli/','adv','adv. 错误地','["wrong"]','["Wrongly accused."]','["wrong"]'),
('w_0931','write','/raɪt/','verb','v. 书写','["writ"]','["Write clearly."]','["writ"]'),
('w_0932','writ','/rɪt/','noun','n. 书面命令','["writ"]','["Court writ."]','["writ"]'),
('w_0933','wrathful','/ˈrɒθfʊl/','adj','adj. 愤怒的','["wrath"]','["Wrathful god."]','["wrath"]'),
('w_0934','wraith','/reɪθ/','noun','n. 幽灵','["wrait"]','["Ghostly wraith."]','["wrait"]'),
('w_0935','xenophobia','/ˌzenəˈfəʊbiə/','noun','n. 仇外','["xeno","phob"]','["Xenophobia rising."]','["xeno","phob"]'),
('w_0936','xenophobic','/ˌzenəˈfəʊbɪk/','adj','adj. 排外的','["xeno","phob"]','["Xenophobic policies."]','["xeno","phob"]'),
('w_0937','xenial','/ˈziːniəl/','adj','adj. 款待的','["xen"]','["Xenial customs."]','["xen"]'),
('w_0938','xenogenesis','/ˌzenəˈdʒenəsɪs/','noun','n. 异源','["xeno","gen"]','["Xenogenesis concept."]','["xeno","gen"]'),
('w_0939','xylophone','/ˈzaɪləfəʊn/','noun','n. 木琴','["xylo","phone"]','["Play xylophone."]','["xylo","phone"]'),
('w_0940','yacht','/jɒt/','noun','n. 游艇','["yacht"]','["Luxury yacht."]','["yacht"]'),
('w_0941','yearn','/jɜːn/','verb','v. 渴望','["yearn"]','["Yearn for freedom."]','["yearn"]'),
('w_0942','yearning','/ˈjɜːnɪŋ/','noun','n. 渴望','["yearn"]','["Deep yearning."]','["yearn"]'),
('w_0943','yeast','/jiːst/','noun','n. 酵母','["yeast"]','["Baker yeast."]','["yeast"]'),
('w_0944','yell','/jel/','verb','v. 叫喊','["yell"]','["Yell at someone."]','["yell"]'),
('w_0945','yellow','/ˈjeləʊ/','adj','adj. 黄色的','["yellow"]','["Yellow color."]','["yellow"]'),
('w_0946','yelp','/jelp/','verb','v. 尖叫','["yelp"]','["Dog yelps."]','["yelp"]'),
('w_0947','yield','/jiːld/','verb','v. 产生','["yield"]','["Yield results."]','["yield"]'),
('w_0948','yoke','/jəʊk/','noun','n. 束缚','["yoke"]','["Yoke of oppression."]','["yoke"]'),
('w_0949','yolk','/jəʊk/','noun','n. 蛋黄','["yolk"]','["Egg yolk."]','["yolk"]'),
('w_0950','yonder','/ˈjɒndər/','adv','adv. 那边','["yond"]','["Look yonder."]','["yond"]'),
('w_0951','young','/jʌŋ/','adj','adj. 年轻的','["young"]','["Young generation."]','["young"]'),
('w_0952','youth','/juːθ/','noun','n. 青年','["youth"]','["Youth culture."]','["youth"]'),
('w_0953','youthful','/ˈjuːθfʊl/','adj','adj. 年轻的','["youth"]','["Youthful energy."]','["youth"]'),
('w_0954','year','/jɪər/','noun','n. 年','["year"]','["This year."]','["year"]'),
('w_0955','yearly','/ˈjɪərli/','adj','adj. 每年的','["year"]','["Yearly income."]','["year"]'),
('w_0956','zeal','/ziːl/','noun','n. 热情','["zeal"]','["Revolutionary zeal."]','["zeal"]'),
('w_0957','zealous','/ˈzeləs/','adj','adj. 热心的','["zeal"]','["Zealous supporter."]','["zeal"]'),
('w_0958','zealot','/ˈzelət/','noun','n. 狂热者','["zeal"]','["Religious zealot."]','["zeal"]'),
('w_0959','zenith','/ˈzenɪθ/','noun','n. 顶点','["zenith"]','["Career zenith."]','["zenith"]'),
('w_0960','zephyr','/ˈzefər/','noun','n. 西风','["zeph"]','["Gentle zephyr."]','["zeph"]'),
('w_0961','zero','/ˈzɪərəʊ/','noun','n. 零','["zero"]','["Temperature zero."]','["zero"]'),
('w_0962','zest','/zest/','noun','n. 热情','["zest"]','["Life zest."]','["zest"]'),
('w_0963','zigzag','/ˈzɪɡzæɡ/','noun','n. 之字形','["zig","zag"]','["Zigzag path."]','["zig","zag"]'),
('w_0964','zinc','/zɪŋk/','noun','n. 锌','["zinc"]','["Zinc supplement."]','["zinc"]'),
('w_0965','zipper','/ˈzɪpər/','noun','n. 拉链','["zipp"]','["Open zipper."]','["zipp"]'),
('w_0966','zip','/zɪp/','verb','v. 压缩','["z"]','["Zip files."]','["z"]'),
('w_0967','zone','/zəʊn/','noun','n. 区域','["zon"]','["Time zone."]','["zon"]'),
('w_0968','zoning','/ˈzəʊnɪŋ/','noun','n. 分区','["zon"]','["City zoning."]','["zon"]'),
('w_0969','zoology','/zəʊˈɒlədʒi/','noun','n. 动物学','["zoo","log"]','["Study zoology."]','["zoo","log"]'),
('w_0970','zoo','/zuː/','noun','n. 动物园','["zoo"]','["Visit zoo."]','["zoo"]'),
('w_0971','zoom','/zuːm/','verb','v. 快速移动','["zoom"]','["Car zooms."]','["zoom"]'),
('w_0972','zealot','/ˈzelət/','noun','n. 狂信者','["zeal"]','["Political zealot."]','["zeal"]'),
('w_0973','zen','/zen/','noun','n. 禅','["zen"]','["Zen Buddhism."]','["zen"]'),
('w_0974','zigzag','/ˈzɪɡzæɡ/','verb','v. 曲折','["zig","zag"]','["Road zigzags."]','["zig","zag"]'),
('w_0975','zip','/zɪp/','noun','n. 拉链','["zip"]','["Close zip."]','["zip"]'),
('w_0976','zealot','/ˈzelət/','noun','n. 热心者','["zeal"]','[" zealous zealot."]','["zeal"]'),
('w_0977','zodiac','/ˈzəʊdiæk/','noun','n. 星座','["zodiac"]','["Zodiac signs."]','["zodiac"]'),
('w_0978','zombie','/ˈzɒmbi/','noun','n. 僵尸','["zomb"]','["Zombie movie."]','["zomb"]'),
('w_0979','zone','/zəʊn/','verb','v. 分区','["zon"]','["Zone for industry."]','["zon"]'),
('w_0980','zany','/ˈzeɪni/','adj','adj. 古怪的','["zan"]','["Zany humor."]','["zan"]'),
('w_0981','zodiacal','/zəʊˈdaɪəkəl/','adj','adj. 星座的','["zodiac"]','["Zodiacal sign."]','["zodiac"]'),
('w_0982','zoological','/ˌzəʊəˈlɒdʒɪkəl/','adj','adj. 动物学的','["zoo","log"]','["Zoological garden."]','["zoo","log"]'),
('w_0983','zygote','/ˈzaɪɡəʊt/','noun','n. 受精卵','["zyg"]','["The zygote develops."]','["zyg"]'),
('w_0984','zealot','/ˈzelət/','noun','n. 极端分子','["zeal"]','["Religious zealot."]','["zeal"]'),
('w_0985','zephyr','/ˈzefər/','noun','n. 和风','["zeph"]','["Summer zephyr."]','["zeph"]'),
('w_0986','zero','/ˈzɪərəʊ/','verb','v. 瞄准','["zero"]','["Zero in on target."]','["zero"]'),
('w_0987','zestful','/ˈzestfʊl/','adj','adj. 热情的','["zest"]','["Zestful performance."]','["zest"]'),
('w_0988','zinc','/zɪŋk/','verb','v. 镀锌','["zinc"]','["Zinc plate."]','["zinc"]'),
('w_0989','zippy','/ˈzɪpi/','adj','adj. 敏捷的','["zipp"]','["Zippy car."]','["zipp"]'),
('w_0990','zip','/zɪp/','noun','n. 邮政编码','["zip"]','["Zip code."]','["zip"]'),
('w_0991','zenith','/ˈzenɪθ/','noun','n. 鼎盛时期','["zenith"]','["At zenith of career."]','["zenith"]'),
('w_0992','zero','/ˈzɪərəʊ/','noun','n. 零钱','["zero"]','["Zero in wallet."]','["zero"]'),
('w_0993','zodiac','/ˈzəʊdiæk/','noun','n. 生肖','["zodiac"]','["Chinese zodiac."]','["zodiac"]'),
('w_0994','zombie','/ˈzɒmbi/','verb','v. 摧毁','["zomb"]','["Zombie company."]','["zomb"]'),
('w_0995','zone','/zəʊn/','noun','n. 气候带','["zon"]','["Cold zone."]','["zon"]'),
('w_0996','zoom','/zuːm/','noun','n. 缩放','["zoom"]','["Camera zoom."]','["zoom"]'),
('w_0997','zeal','/ziːl/','noun','n. 激情','["zeal"]','["Patriotic zeal."]','["zeal"]'),
('w_0998','yearn','/jɜːn/','verb','v. 思念','["yearn"]','["Yearn for home."]','["yearn"]'),
('w_0999','yeast','/jiːst/','verb','v. 发酵','["yeast"]','["Dough yeasts."]','["yeast"]'),
('w_1000','yield','/jiːld/','noun','n. 产量','["yield"]','["Crop yield."]','["yield"]');
