-- 添加词汇 701-800
INSERT INTO words (word_id, word, phonetic, pos, definition, family, examples, roots) VALUES
('w_0701','malignant','/məˈlɪɡnənt/','adj','adj. 恶性的','["mal"]','["Malignant tumor."]','["mal","ign"]'),
('w_0702','malice','/ˈmælɪs/','noun','n. 恶意','["mal"]','["bear malice."]','["mal"]'),
('w_0703','malicious','/məˈlɪʃəs/','adj','adj. 恶意的','["mal"]','["Malicious intent."]','["mal"]'),
('w_0704','malign','/məˈlaɪn/','adj','adj. 邪恶的','["mal"]','["Malign influence."]','["mal"]'),
('w_0705','malnutrition','/mælnjʊˈtrɪʃən/','noun','n. 营养不良','["mal","nutri"]','["Child malnutrition."]','["mal","nutri"]'),
('w_0706','malpractice','/mælˈpræktɪs/','noun','n. 渎职','["mal","pract"]','["Medical malpractice."]','["mal","pract"]'),
('w_0707','malfunction','/mælˈfʌŋkʃən/','noun','n. 故障','["mal","func"]','["Equipment malfunction."]','["mal","func"]'),
('w_0708','malaise','/məˈleɪz/','noun','n. 不适','["mal"]','["Economic malaise."]','["mal"]'),
('w_0709','maladapt','/mæləˈdæpt/','verb','v. 不适应','["mal","adap"]','["Maladapt to climate."]','["mal","adap"]'),
('w_0710','malcontent','/ˈmælkəntent/','adj','adj. 不满的','["mal","con"]','["Malcontent rebels."]','["mal","con"]'),
('w_0711','bilateral','/baɪˈlætərəl/','adj','adj. 双边的','["bi","later"]','["Bilateral agreement."]','["bi","later"]'),
('w_0712','unilateral','/juːnɪˈlætərəl/','adj','adj. 单方面的','["uni","later"]','["Unilateral decision."]','["uni","later"]'),
('w_0713','lateral','/ˈlætərəl/','adj','adj. 侧面的','["later"]','["Lateral thinking."]','["later"]'),
('w_0714','equilateral','/ˌiːkwɪˈlætərəl/','adj','adj. 等边的','["equi","later"]','["Equilateral triangle."]','["equi","later"]'),
('w_0715','collateral','/kəˈlætərəl/','noun','n. 抵押品','["col","later"]','["Collateral for loan."]','["col","later"]'),
('w_0716','literal','/ˈlɪtərəl/','adj','adj. 字面的','["liter"]','["Literal meaning."]','["liter"]'),
('w_0717','literary','/ˈlɪtərəri/','adj','adj. 文学的','["liter"]','["Literary works."]','["liter"]'),
('w_0718','literate','/ˈlɪtərət/','adj','adj. 有文化的','["liter"]','["Computer literate."]','["liter"]'),
('w_0719','illiterate','/ɪˈlɪtərət/','adj','adj. 文盲的','["il","liter"]','["Functional illiterate."]','["il","liter"]'),
('w_0720','literacy','/ˈlɪtərəsi/','noun','n. 识字','["liter"]','["Financial literacy."]','["liter"]'),
('w_0721','obliterate','/əˈblɪtəreɪt/','verb','v. 抹去','["ob","liter"]','["Obliterate evidence."]','["ob","liter"]'),
('w_0722','transliterate','/trænzˈlɪtəreɪt/','verb','v. 音译','["trans","liter"]','["Transliterate names."]','["trans","liter"]'),
('w_0723','alliteration','/əˌlɪtəˈreɪʃən/','noun','n. 头韵','["al","liter"]','["Use alliteration."]','["al","liter"]'),
('w_0724','malice','/ˈmælɪs/','noun','n. 恶意','["mal"]','["With malice."]','["mal"]'),
('w_0725','mobility','/məʊˈbɪlɪti/','noun','n. 流动性','["mob"]','["Social mobility."]','["mob"]'),
('w_0726','mobilize','/ˈməʊbɪlaɪz/','verb','v. 动员','["mob"]','["Mobilize resources."]','["mob"]'),
('w_0727','automobile','/ˈɔːtəməbiːl/','noun','n. 汽车','["auto","mob"]','["Drive automobile."]','["auto","mob"]'),
('w_0728','demobilize','/diːˈməʊbɪlaɪz/','verb','v. 复员','["de","mob"]','["Demobilize troops."]','["de","mob"]'),
('w_0729','mob','/mɒb/','noun','n. 暴民','["mob"]','["Angry mob."]','["mob"]'),
('w_0730','mobster','/ˈmɒbstər/','noun','n. 匪徒','["mob"]','["Organized mobster."]','["mob"]'),
('w_0731','commemorate','/kəˈmeməreɪt/','verb','v. 纪念','["com","mem"]','["Commemorate heroes."]','["com","mem"]'),
('w_0732','memorial','/məˈmɔːriəl/','noun','n. 纪念馆','["mem"]','["War memorial."]','["mem"]'),
('w_0733','memory','/ˈmeməri/','noun','n. 记忆','["mem"]','["Strong memory."]','["mem"]'),
('w_0734','memorable','/ˈmemərəbl/','adj','adj. 值得纪念的','["mem"]','["Memorable event."]','["mem"]'),
('w_0735','immortal','/ɪˈmɔːtəl/','adj','adj. 不朽的','["im","mort"]','["Immortal soul."]','["im","mort"]'),
('w_0736','mortal','/ˈmɔːtəl/','adj','adj. 终有一死的','["mort"]','["All mortals."]','["mort"]'),
('w_0737','mortgage','/ˈmɔːɡɪdʒ/','noun','n. 抵押贷款','["mort","gage"]','["Pay mortgage."]','["mort","gage"]'),
('w_0738','mortify','/ˈmɔːtɪfaɪ/','verb','v. 使蒙羞','["mort","ify"]','["Feel mortified."]','["mort","ify"]'),
('w_0739','postmortem','/pəʊstˈmɔːtəm/','adj','adj. 死后的','["post","mort"]','["Postmortem examination."]','["post","mort"]'),
('w_0740','morbid','/ˈmɔːbɪd/','adj','adj. 病态的','["mor"]','["Morbid interest."]','["mor"]'),
('w_0741','amor','/ˈeɪmɔːr/','noun','n. 爱情','["am"]','["Amor patrio."]','["am"]'),
('w_0742','amiable','/ˈeɪmiəbl/','adj','adj. 和蔼的','["am"]','["Amiable personality."]','["am"]'),
('w_0743','amorous','/ˈæmərəs/','adj','adj. 多情的','["am"]','["Amorous affairs."]','["am"]'),
('w_0744','enmity','/ˈenmɪti/','noun','n. 敌意','["en"]','["Bitter enmity."]','["en"]'),
('w_0745','enemy','/ˈenəmi/','noun','n. 敌人','["en"]','["Public enemy."]','["en"]'),
('w_0746','neutral','/ˈnjuːtrəl/','adj','adj. 中立的','["ne","utr"]','["Neutral stance."]','["ne","utr"]'),
('w_0747','neutralize','/ˈnjuːtrəlaɪz/','verb','v. 使中立','["ne","utr"]','["Neutralize threats."]','["ne","utr"]'),
('w_0748','neuter','/ˈnjuːtər/','adj','adj. 中性的','["ne","utr"]','["Neuter gender."]','["ne","utr"]'),
('w_0749','nuclear','/ˈnjuːkliər/','adj','adj. 核能的','["nuc"]','["Nuclear power."]','["nuc"]'),
('w_0750','nucleus','/ˈnjuːkliəs/','noun','n. 原子核','["nuc"]','["Cell nucleus."]','["nuc"]'),
('w_0751','nucleate','/ˈnjuːklɪeɪt/','verb','v. 成核','["nuc"]','["Nucleate crystals."]','["nuc"]'),
('w_0752','oblong','/ˈɒblɒŋ/','noun','n. 长方形','["ob","long"]','["Oblong shape."]','["ob","long"]'),
('w_0753','obloquy','/ˈɒbləkwi/','noun','n. 诽谤','["ob","loqu"]','["Public obloquy."]','["ob","loqu"]'),
('w_0754','eloquent','/ˈeləkwənt/','adj','adj. 雄辩的','["e","loqu"]','["Eloquent speaker."]','["e","loqu"]'),
('w_0755','colloquial','/kəˈləʊkwiəl/','adj','adj. 口语的','["col","loqu"]','["Colloquial language."]','["col","loqu"]'),
('w_0756','soliloquy','/səˈlɪləkwi/','noun','n. 独白','["sol","loqu"]','["Theatrical soliloquy."]','["sol","loqu"]'),
('w_0757','eloquence','/ˈeləkwəns/','noun','n. 雄辩','["e","loqu"]','["Speech eloquence."]','["e","loqu"]'),
('w_0758','obscene','/əbˈsiːn/','adj','adj. 淫秽的','["ob","scene"]','["Obscene language."]','["ob","scene"]'),
('w_0759','obscure','/əbˈskjʊər/','adj','adj. 模糊的','["ob","scure"]','["Obscure meaning."]','["ob","scure"]'),
('w_0760','obsolete','/ˈɒbsəliːt/','adj','adj. 过时的','["ob","sol"]','["Obsolete technology."]','["ob","sol"]'),
('w_0761','obstacle','/ˈɒbstəkl/','noun','n. 障碍','["ob","st"]','["Obstacle to progress."]','["ob","st"]'),
('w_0762','obstruct','/əbˈstrʌkt/','verb','v. 阻塞','["ob","struct"]','["Obstruct traffic."]','["ob","struct"]'),
('w_0763','obstruction','/əbˈstrʌkʃən/','noun','n. 障碍物','["ob","struct"]','["Political obstruction."]','["ob","struct"]'),
('w_0764','obstreperous','/əbˈstreprəs/','adj','adj. 吵闹的','["ob","streper"]','["Obstreperous children."]','["ob","streper"]'),
('w_0765','obtrude','/əbˈtruːd/','verb','v. 强迫','["ob","trude"]','["Obtrude opinions."]','["ob","trude"]'),
('w_0766','obtrusive','/əbˈtruːsɪv/','adj','adj. 突出的','["ob","trus"]','["Obtrusive design."]','["ob","trus"]'),
('w_0767','intrude','/ɪnˈtruːd/','verb','v. 入侵','["in","trude"]','["Intrude on privacy."]','["in","trude"]'),
('w_0768','extrude','/ɪkˈstruːd/','verb','v. 挤出','["ex","trude"]','["Extrude plastic."]','["ex","trude"]'),
('w_0769','protrude','/prəˈtruːd/','verb','v. 突出','["pro","trude"]','["Protrude from wall."]','["pro","trude"]'),
('w_0770','detrude','/dɪˈtruːd/','verb','v. 推落','["de","trude"]','["Detrude from position."]','["de","trude"]'),
('w_0771','abstruse','/æbˈstruːs/','adj','adj. 难懂的','["abs","truse"]','["Abstruse theory."]','["abs","truse"]'),
('w_0772','obverse','/ˈɒbvɜːs/','noun','n. 正面','["ob","verse"]','["Coin obverse."]','["ob","verse"]'),
('w_0773','adverse','/ˈædvɜːs/','adj','adj. 敌对的','["ad","verse"]','["Adverse weather."]','["ad","verse"]'),
('w_0774','reverse','/rɪˈvɜːs/','verb','v. 颠倒','["re","verse"]','["Reverse decision."]','["re","verse"]'),
('w_0775','converse','/kənˈvɜːs/','verb','v. 交谈','["con","verse"]','["Converse in English."]','["con","verse"]'),
('w_0776','diverse','/daɪˈvɜːs/','adj','adj. 不同的','["di","verse"]','["Diverse cultures."]','["di","verse"]'),
('w_0777','perverse','/pəˈvɜːs/','adj','adj. 堕落的','["per","verse"]','["Perverse behavior."]','["per","verse"]'),
('w_0778','traverse','/ˈtrævəs/','verb','v. 横穿','["tra","verse"]','["Traverse the desert."]','["tra","verse"]'),
('w_0779','universe','/ˈjuːnɪvɜːs/','noun','n. 宇宙','["uni","verse"]','["Expand universe."]','["uni","verse"]'),
('w_0780','university','/ˌjuːnɪˈvɜːsɪti/','noun','n. 大学','["uni","vers"]','["Top university."]','["uni","vers"]'),
('w_0781','versatile','/ˈvɜːsətaɪl/','adj','adj. 多才多艺的','["vers"]','["Versatile athlete."]','["vers"]'),
('w_0782','version','/ˈvɜːʃən/','noun','n. 版本','["vers"]','["Software version."]','["vers"]'),
('w_0783','versus','/ˈvɜːsəs/','prep','prep. 对','["vers"]','["China versus US."]','["vers"]'),
('w_0784','vertical','/ˈvɜːtɪkəl/','adj','adj. 垂直的','["vert"]','["Vertical line."]','["vert"]'),
('w_0785','vertigo','/ˈvɜːtɪɡəʊ/','noun','n. 眩晕','["vert"]','["Height vertigo."]','["vert"]'),
('w_0786','avert','/əˈvɜːt/','verb','v. 避免','["a","vert"]','["Avert disaster."]','["a","vert"]'),
('w_0787','advert','/ˈædvɜːt/','noun','n. 广告','["ad","vert"]','["Job advert."]','["ad","vert"]'),
('w_0788','convert','/kənˈvɜːt/','verb','v. 转换','["con","vert"]','["Convert currency."]','["con","vert"]'),
('w_0789','divert','/daɪˈvɜːt/','verb','v. 转移','["di","vert"]','["Divert traffic."]','["di","vert"]'),
('w_0790','invert','/ɪnˈvɜːt/','verb','v. 反转','["in","vert"]','["Invert image."]','["in","vert"]'),
('w_0791','pervert','/pəˈvɜːt/','verb','v. 曲解','["per","vert"]','["Pervert truth."]','["per","vert"]'),
('w_0792','revert','/rɪˈvɜːt/','verb','v. 恢复','["re","vert"]','["Revert to default."]','["re","vert"]'),
('w_0793','subvert','/səbˈvɜːt/','verb','v. 颠覆','["sub","vert"]','["Subvert regime."]','["sub","vert"]'),
('w_0794','transvert','/trænzˈvɜːt/','verb','v. 转变','["trans","vert"]','["Transvert form."]','["trans","vert"]'),
('w_0795','advocate','/ˈædvəkət/','verb','v. 提倡','["ad","voc"]','["Advocate peace."]','["ad","voc"]'),
('w_0796','vocabulary','/vəˈkæbjʊləri/','noun','n. 词汇','["voc"]','["Expand vocabulary."]','["voc"]'),
('w_0797','vocal','/ˈvəʊkəl/','adj','adj. 声音的','["voc"]','["Vocal cords."]','["voc"]'),
('w_0798','vocation','/vəʊˈkeɪʃən/','noun','n. 职业','["voc"]','["Career vocation."]','["voc"]'),
('w_0799','equivocate','/ɪˈkwɪvəkeɪt/','verb','v. 模棱两可','["equi","voc"]','["Equivocate answer."]','["equi","voc"]'),
('w_0800','invoke','/ɪnˈvəʊk/','verb','v. 调用','["in","vok"]','["Invoke law."]','["in","vok"]');
