-- 添加词汇 401-500
INSERT INTO words (word_id, word, phonetic, pos, definition, family, examples, roots) VALUES
('w_0401','compatible','/kəmˈpætɪbl/','adj','adj. 兼容的','[]','["Compatible with Windows."]','["com","pat"]'),
('w_0402','patience','/ˈpeɪʃəns/','noun','n. 耐心','[]','["Have patience."]','["pat"]'),
('w_0403','patient','/ˈpeɪʃənt/','adj','adj. 耐心的','[]','["Be patient."]','["pat"]'),
('w_0404','impatient','/ɪmˈpeɪʃənt/','adj','adj. 不耐烦的','[]','["Impatient with delays."]','["im","pat"]'),
('w_0405','compatible','/kəmˈpætɪbl/','adj','adj. 和谐的','[]','["Compatible couple."]','["com","pat"]'),
('w_0406','patron','/ˈpeɪtrən/','noun','n. 赞助人','[]','["Patron of the arts."]','["pat"]'),
('w_0407','patronize','/ˈpætrənaɪz/','verb','v. 资助','[]','["Patronize the store."]','["pat"]'),
('w_0408','compatriot','/kəmˈpætriət/','noun','n. 同胞','[]','["Fellow compatriot."]','["com","pat"]'),
('w_0409','patrimony','/ˈpætrɪməni/','noun','n. 遗产','[]','["Cultural patrimony."]','["pat"]'),
('w_0410','patriot','/ˈpeɪtriət/','noun','n. 爱国者','[]','["A true patriot."]','["pat"]'),
('w_0411','patriotic','/ˌpeɪtriˈɒtɪk/','adj','adj. 爱国的','[]','["Patriotic song."]','["pat"]'),
('w_0412','patriotism','/ˈpeɪtriətɪzəm/','noun','n. 爱国主义','[]','["Show patriotism."]','["pat"]'),
('w_0413','impair','/ɪmˈpeər/','verb','v. 损害','[]','["Impair health."]','["im","pair"]'),
('w_0414','repair','/rɪˈpeər/','verb','v. 修理','[]','["Repair the car."]','["re","pair"]'),
('w_0415','pair','/peər/','noun','n. 一对','[]','["A pair of shoes."]','["pair"]'),
('w_0416','repair','/rɪˈpeər/','noun','n. 修理','[]','["Under repair."]','["re"]'),
('w_0417','despair','/dɪˈspeər/','noun','n. 绝望','[]','["Fall into despair."]','["de","spair"]'),
('w_0418','separate','/ˈsepərət/','adj','adj. 分开的','[]','["Live separate lives."]','["se","par"]'),
('w_0419','separate','/ˈsepəreɪt/','verb','v. 分开','[]','["Separate the components."]','["se","par"]'),
('w_0420','separately','/ˈsepərətli/','adv','adv. 分别地','[]','["Handle separately."]','["se","par"]'),
('w_0421','separation','/ˌsepəˈreɪʃən/','noun','n. 分离','[]','["Separation of church and state."]','["se","par"]'),
('w_0422','apparatus','/ˌæpəˈreɪtəs/','noun','n. 设备','[]','["Laboratory apparatus."]','["ap","par"]'),
('w_0423','prepare','/prɪˈpeər/','verb','v. 准备','[]','["Prepare dinner."]','["pre","par"]'),
('w_0424','prepared','/prɪˈpeəd/','adj','adj. 准备好的','[]','["Be prepared."]','["pre","par"]'),
('w_0425','preparation','/ˌprepəˈreɪʃən/','noun','n. 准备','[]','["Preparation for exam."]','["pre","par"]'),
('w_0426','repair','/rɪˈpeər/','verb','v. 补救','[]','["Repair the situation."]','["re"]'),
('w_0427','reparations','/ˌrepəˈreɪʃənz/','noun','n. 赔偿','[]','["War reparations."]','["re","par"]'),
('w_0428','comparable','/ˈkɒmpərəbl/','adj','adj. 可比的','[]','["Comparable quality."]','["com","par"]'),
('w_0429','comparative','/kəmˈpærətɪv/','adj','adj. 比較的','[]','["Comparative study."]','["com","par"]'),
('w_0430','compare','/kəmˈpeər/','verb','v. 比较','[]','["Compare prices."]','["com","par"]'),
('w_0431','comparison','/kəmˈpærɪsən/','noun','n. 比较','[]','["Fair comparison."]','["com","par"]'),
('w_0432','disparity','/dɪˈspærɪti/','noun','n. 不平等','[]','["Economic disparity."]','["dis","par"]'),
('w_0433','parity','/ˈpærɪti/','noun','n. 平等','[]','["Gender parity."]','["par"]'),
('w_0434','separate','/ˈsepərət/','adj','adj. 各自的','[]','["Separate bedrooms."]','["se"]'),
('w_0435','impart','/ɪmˈpɑːt/','verb','v. 传授','[]','["Impart knowledge."]','["im","part"]'),
('w_0436','part','/pɑːt/','noun','n. 部分','[]','["Part of the whole."]','["part"]'),
('w_0437','partial','/ˈpɑːʃəl/','adj','adj. 部分的','[]','["Partial payment."]','["part"]'),
('w_0438','partially','/ˈpɑːʃəli/','adv','adv. 部分地','[]','["Partially true."]','["part"]'),
('w_0439','participate','/pɑːˈtɪsɪpeɪt/','verb','v. 参与','[]','["Participate in event."]','["part","cip"]'),
('w_0440','participant','/pɑːˈtɪsɪpənt/','noun','n. 参与者','[]','["Event participant."]','["part","cip"]'),
('w_0441','participation','/pɑːˌtɪsɪˈpeɪʃən/','noun','n. 参与','[]','["Active participation."]','["part","cip"]'),
('w_0442','particle','/ˈpɑːtɪkl/','noun','n. 粒子','[]','["Dust particles."]','["part"]'),
('w_0443','partner','/ˈpɑːtnər/','noun','n. 伙伴','[]','["Business partner."]','["part"]'),
('w_0444','partnership','/ˈpɑːtnəʃɪp/','noun','n. 合作关系','[]','["Strategic partnership."]','["part"]'),
('w_0445','apartment','/əˈpɑːtmənt/','noun','n. 公寓','[]','["City apartment."]','["a","part"]'),
('w_0446','department','/dɪˈpɑːtmənt/','noun','n. 部门','[]','["Sales department."]','["de","part"]'),
('w_0447','depart','/dɪˈpɑːt/','verb','v. 离开','[]','["Depart at noon."]','["de","part"]'),
('w_0448','departure','/dɪˈpɑːtʃər/','noun','n. 出发','[]','["Departure time."]','["de","part"]'),
('w_0449','impart','/ɪmˈpɑːt/','verb','v. 给予','[]','["Impart wisdom."]','["im"]'),
('w_0450','particular','/pəˈtɪkjʊlər/','adj','adj. 特定的','[]','["In particular."]','["part"]'),
('w_0451','particularly','/pəˈtɪkjʊlərli/','adv','adv. 特别地','[]','["Particularly important."]','["part"]'),
('w_0452','party','/ˈpɑːti/','noun','n. 政党','[]','["Political party."]','["part"]'),
('w_0453','passage','/ˈpæsɪdʒ/','noun','n. 通道','[]','["Mountain passage."]','["pass"]'),
('w_0454','passenger','/ˈpæsɪndʒər/','noun','n. 乘客','[]','["Train passenger."]','["pass"]'),
('w_0455','passion','/ˈpæʃən/','noun','n. 激情','[]','["Passion for music."]','["pass"]'),
('w_0456','passive','/ˈpæsɪv/','adj','adj. 被动的','[]','["Passive smoking."]','["pass"]'),
('w_0457','passport','/ˈpɑːspɔːt/','noun','n. 护照','[]','["Valid passport."]','["pass","port"]'),
('w_0458','password','/ˈpɑːswɜːd/','noun','n. 密码','[]','["Strong password."]','["pass","word"]'),
('w_0459','bypass','/ˈbaɪpɑːs/','verb','v. 绕过','[]','["Bypass the system."]','["by","pass"]'),
('w_0460','overpass','/ˈəʊvəpɑːs/','noun','n. 天桥','[]','["Highway overpass."]','["over","pass"]'),
('w_0461','surpass','/səˈpɑːs/','verb','v. 超越','[]','["Surpass expectations."]','["sur","pass"]'),
('w_0462','impassable','/ɪmˈpɑːsəbl/','adj','adj. 不能通行的','[]','["Impassable road."]','["im","pass"]'),
('w_0463','compassion','/kəmˈpæʃən/','noun','n. 同情','[]','["Show compassion."]','["com","pass"]'),
('w_0464','compatible','/kəmˈpætɪbl/','adj','adj. 一致的','[]','["Compatible views."]','["com","pat"]'),
('w_0465','patience','/ˈpeɪʃəns/','noun','n. 忍耐','[]','["Test patience."]','["pat"]'),
('w_0466','patient','/ˈpeɪʃənt/','adj','adj. 忍耐的','[]','["Patient listener."]','["pat"]'),
('w_0467','impatient','/ɪmˈpeɪʃənt/','adj','adj. 急躁的','[]','["Impatient attitude."]','["im","pat"]'),
('w_0468','compatible','/kəmˈpætɪbl/','adj','adj. 协调的','[]','["Compatible colors."]','["com"]'),
('w_0469','pass','/pɑːs/','verb','v. 通过','[]','["Pass the exam."]','["pass"]'),
('w_0470','pass','/pɑːs/','noun','n. 通行证','[]','["Mountain pass."]','["pass"]'),
('w_0471','passing','/ˈpɑːsɪŋ/','adj','adj. 短暂的','[]','["Passing fancy."]','["pass"]'),
('w_0472','past','/pɑːst/','noun','n. 过去','[]','["Learn from the past."]','["pass"]'),
('w_0473','paste','/peɪst/','noun','n. 糊状物','[]','["Toothpaste."]','["pas"]'),
('w_0474','pastime','/ˈpɑːstaɪm/','noun','n. 消遣','[]','["Favorite pastime."]','["pas","time"]'),
('w_0475','broadcast','/ˈbrɔːdkɑːst/','verb','v. 广播','[]','["Broadcast news."]','["broad","cast"]'),
('w_0476','forecast','/ˈfɔːkɑːst/','noun','n. 预报','[]','["Weather forecast."]','["fore","cast"]'),
('w_0477','newscast','/ˈnjuːzkɑːst/','noun','n. 新闻广播','[]','["Evening newscast."]','["news","cast"]'),
('w_0478','typecast','/ˈtaɪpkɑːst/','verb','v. 分配角色','[]','["Typecast actor."]','["type","cast"]'),
('w_0479','cast','/kɑːst/','verb','v. 投射','[]','["Cast a shadow."]','["cast"]'),
('w_0480','forecast','/ˈfɔːkɑːst/','verb','v. 预测','[]','["Forecast sales."]','["fore"]'),
('w_0481','forecast','/ˈfɔːkɑːst/','noun','n. 预测','[]','["Sales forecast."]','["fore"]'),
('w_0482','caster','/ˈkɑːstər/','noun','n. 投手','[]','["Sugar caster."]','["cast"]'),
('w_0483','casting','/ˈkɑːstɪŋ/','noun','n. 铸造','[]','["Casting process."]','["cast"]'),
('w_0484','broadcast','/ˈbrɔːdkɑːst/','noun','n. 广播','[]','["Live broadcast."]','["broad"]'),
('w_0485','pilaster','/pɪˈlæstər/','noun','n. 壁柱','[]','["Decorative pilaster."]','["pil"]'),
('w_0486','master','/ˈmɑːstər/','noun','n. 主人','[]','["Master of ceremonies."]','["mast"]'),
('w_0487','masterpiece','/ˈmɑːstəpiːs/','noun','n. 杰作','[]','["Art masterpiece."]','["master","piece"]'),
('w_0488','masterful','/ˈmɑːstəfʊl/','adj','adj. 熟练的','[]','["Masterful performance."]','["master"]'),
('w_0489','mastermind','/ˈmɑːstəmaɪnd/','noun','n. 策划者','[]','["Criminal mastermind."]','["master","mind"]'),
('w_0490','masterwork','/ˈmɑːstəwɜːk/','noun','n. 名著','[]','["Literary masterwork."]','["master","work"]'),
('w_0491','mistress','/ˈmɪstrəs/','noun','n. 女主人','[]','["Mistress of the house."]','["mis"]'),
('w_0492','masthead','/ˈmɑːsthed/','noun','n. 报头','[]','["Newspaper masthead."]','["mast","head"]'),
('w_0493','mast','/mɑːst/','noun','n. 桅杆','[]','["Ship mast."]','["mast"]'),
('w_0494','robust','/rəʊˈbʌst/','adj','adj. 强壮的','[]','["Robust health."]','["rob"]'),
('w_0495','obsolete','/ˈɒbsəliːt/','adj','adj. 过时的','[]','["Obsolete technology."]','["ob","sol"]'),
('w_0496','obstacle','/ˈɒbstəkl/','noun','n. 障碍','[]','["Obstacle race."]','["ob","st"]'),
('w_0497','obstruct','/əbˈstrʌkt/','verb','v. 阻挡','[]','["Obstruct justice."]','["ob","struct"]'),
('w_0498','obstruction','/əbˈstrʌkʃən/','noun','n. 障碍物','[]','["Traffic obstruction."]','["ob","struct"]'),
('w_0499','absurd','/əbˈsɜːd/','adj','adj. 荒谬的','[]','["Absurd idea."]','["ab","surd"]'),
('w_0500','absurdity','/əbˈsɜːdɪti/','noun','n. 荒谬','[]','["The absurdity of it."]','["ab","surd"]');
