-- 添加词汇 1001-1100 (常用词根前缀扩展)
INSERT INTO words (word_id, word, phonetic, pos, definition, family, examples, roots) VALUES
('w_1001','accede','/əkˈsiːd/','verb','v. 同意','["ac","ced"]','["Accede to request."]','["ac","ced"]'),
('w_1002','antecedent','/ˌæntɪˈsiːdənt/','noun','n. 前例','["ante","ced"]','["Historical antecedent."]','["ante","ced"]'),
('w_1003','concede','/kənˈsiːd/','verb','v. 让步','["con","ced"]','["Concede defeat."]','["con","ced"]'),
('w_1004','exceed','/ɪkˈsiːd/','verb','v. 超过','["ex","ced"]','["Exceed expectations."]','["ex","ced"]'),
('w_1005','precede','/prɪˈsiːd/','verb','v. 先于','["pre","ced"]','["Precede the event."]','["pre","ced"]'),
('w_1006','proceed','/prəˈsiːd/','verb','v. 进行','["pro","ced"]','["Proceed with plan."]','["pro","ced"]'),
('w_1007','recede','/rɪˈsiːd/','verb','v. 后退','["re","ced"]','["Waters recede."]','["re","ced"]'),
('w_1008','secede','/sɪˈsiːd/','verb','v. 退出','["se","ced"]','["Secede from union."]','["se","ced"]'),
('w_1009','ancestor','/ˈænsəstər/','noun','n. 祖先','["ance"]','["Common ancestor."]','["ance"]'),
('w_1010','ancient','/ˈeɪnʃənt/','adj','adj. 古代的','["ance"]','["Ancient civilization."]','["ance"]'),
('w_1011','precede','/prɪˈsiːd/','verb','v. 领先','["pre","ced"]','["Precede in time."]','["pre"]'),
('w_1012','process','/ˈprəʊses/','noun','n. 过程','["pro","cess"]','["Manufacturing process."]','["pro","cess"]'),
('w_1013','process','/prəˈses/','verb','v. 处理','["pro","cess"]','["Process data."]','["pro","cess"]'),
('w_1014','access','/ˈækses/','noun','n. 通道','["ac","cess"]','["Access denied."]','["ac","cess"]'),
('w_1015','accessible','/əkˈsesəbl/','adj','adj. 可进入的','["ac","cess"]','[" wheelchair accessible."]','["ac","cess"]'),
('w_1016','excess','/ɪkˈses/','noun','n. 超过','["ex","cess"]','["Excess inventory."]','["ex","cess"]'),
('w_1017','excessive','/ɪkˈsesɪv/','adj','adj. 过度的','["ex","cess"]','["Excessive drinking."]','["ex","cess"]'),
('w_1018','recess','/rɪˈses/','noun','n. 休息','["re","cess"]','["Lunch recess."]','["re","cess"]'),
('w_1019','concession','/kənˈseʃən/','noun','n. 让步','["con","cess"]','["Make concession."]','["con","cess"]'),
('w_1020','procession','/prəˈseʃən/','noun','n. 队伍','["pro","cess"]','["Funeral procession."]','["pro","cess"]'),
('w_1021','aggressive','/əˈɡresɪv/','adj','adj. 侵略性的','["ag","gress"]','["Aggressive behavior."]','["ag","gress"]'),
('w_1022','congress','/ˈkɒŋɡres/','noun','n. 国会','["con","gress"]','["US Congress."]','["con","gress"]'),
('w_1023','digress','/daɪˈɡres/','verb','v. 跑题','["di","gress"]','["Digress from topic."]','["di","gress"]'),
('w_1024','egress','/ˈiːɡres/','noun','n. 出口','["e","gress"]','["Emergency egress."]','["e","gress"]'),
('w_1025','ingress','/ˈɪnɡres/','noun','n. 入口','["in","gress"]','["Secure ingress."]','["in","gress"]'),
('w_1026','progress','/ˈprɒɡres/','noun','n. 进步','["pro","gress"]','["Make progress."]','["pro","gress"]'),
('w_1027','regress','/rɪˈɡres/','verb','v. 退步','["re","gress"]','[" regress to old habits."]','["re","gress"]'),
('w_1028','transgress','/trænzˈɡres/','verb','v. 违反','["trans","gress"]','["Transgress the law."]','["trans","gress"]'),
('w_1029','degree','/dɪˈɡriː/','noun','n. 程度','["de","grees"]','["University degree."]','["de","grees"]'),
('w_1030','graduate','/ˈɡrædʒʊət/','verb','v. 毕业','["grad"]','["Graduate college."]','["grad"]'),
('w_1031','undergraduate','/ˌʌndəˈɡrædʒʊət/','noun','n. 大学生','["under","grad"]','["Undergraduate student."]','["under","grad"]'),
('w_1032','gradual','/ˈɡrædʒʊəl/','adj','adj. 逐渐的','["grad"]','["Gradual change."]','["grad"]'),
('w_1033','upgrade','/ʌpˈɡreɪd/','verb','v. 升级','["up","grade"]','["Upgrade software."]','["up","grade"]'),
('w_1034','downgrade','/daʊnˈɡreɪd/','verb','v. 降级','["down","grade"]','["Downgrade rating."]','["down","grade"]'),
('w_1035','ingredient','/ɪnˈɡriːdɪənt/','noun','n. 成分','["in","gred"]','["Food ingredients."]','["in","gred"]'),
('w_1036','agriculture','/ˈæɡrɪkʌltʃər/','noun','n. 农业','["agri","cult"]','["Modern agriculture."]','["agri","cult"]'),
('w_1037','cultivate','/ˈkʌltɪveɪt/','verb','v. 培养','["cult"]','["Cultivate skills."]','["cult"]'),
('w_1038','culture','/ˈkʌltʃər/','noun','n. 文化','["cult"]','["World culture."]','["cult"]'),
('w_1039','sculpture','/ˈskʌlptʃər/','noun','n. 雕塑','["sculpt"]','["Stone sculpture."]','["sculpt"]'),
('w_1040','cult','/kʌlt/','noun','n. 邪教','["cult"]','["Religious cult."]','["cult"]'),
('w_1041','colony','/ˈkɒləni/','noun','n. 殖民地','["colony"]','["Former colony."]','["colony"]'),
('w_1042','colonial','/kəˈləʊniəl/','adj','adj. 殖民的','["colony"]','["Colonial history."]','["colony"]'),
('w_1043','colonize','/ˈkɒlənaɪz/','verb','v. 殖民','["colony"]','["Colonize territory."]','["colony"]'),
('w_1044','migrate','/maɪˈɡreɪt/','verb','v. 迁移','["migr"]','["Birds migrate."]','["migr"]'),
('w_1045','immigrate','/ˈɪmɪɡreɪt/','verb','v. 移入','["im","migr"]','["Immigrate to America."]','["im","migr"]'),
('w_1046','emigrate','/ˈemɪɡreɪt/','verb','v. 移出','["e","migr"]','["Emigrate from China."]','["e","migr"]'),
('w_1047','transplant','/trænsˈplɑːnt/','verb','v. 移植','["trans","plant"]','["Transplant organs."]','["trans","plant"]'),
('w_1048','plant','/plɑːnt/','noun','n. 植物','["plant"]','["Green plants."]','["plant"]'),
('w_1049','plantation','/plænˈteɪʃən/','noun','n. 种植园','["plant"]','["Coffee plantation."]','["plant"]'),
('w_1050','implant','/ɪmˈplɑːnt/','verb','v. 植入','["im","plant"]','["Implant device."]','["im","plant"]'),
('w_1051','supplement','/ˈsʌplɪmənt/','verb','v. 补充','["sup","ple"]','["Supplement diet."]','["sup","ple"]'),
('w_1052','implement','/ˈɪmplɪmənt/','verb','v. 实施','["im","ple"]','["Implement policy."]','["im","ple"]'),
('w_1053','complement','/ˈkɒmplɪmənt/','verb','v. 补足','["com","ple"]','["Complement each other."]','["com","ple"]'),
('w_1054','accomplish','/əˈkʌmplɪʃ/','verb','v. 完成','["ac","compl"]','["Accomplish goals."]','["ac","compl"]'),
('w_1055','complete','/kəmˈpliːt/','adj','adj. 完整的','["com","ple"]','["Complete information."]','["com","ple"]'),
('w_1056','supply','/səˈplaɪ/','verb','v. 供应','["sup","ply"]','["Supply food."]','["sup","ply"]'),
('w_1057','reply','/rɪˈplaɪ/','verb','v. 回复','["re","ply"]','["Reply to email."]','["re","ply"]'),
('w_1058','apply','/əˈplaɪ/','verb','v. 申请','["ap","ply"]','["Apply for job."]','["ap","ply"]'),
('w_1059','comply','/kəmˈplaɪ/','verb','v. 遵守','["com","ply"]','["Comply with rules."]','["com","ply"]'),
('w_1060','imply','/ɪmˈplaɪ/','verb','v. 暗示','["im","ply"]','["What do you imply?"]','["im","ply"]'),
('w_1061','multiply','/ˈmʌltɪplaɪ/','verb','v. 乘以','["multi","ply"]','["Multiply numbers."]','["multi","ply"]'),
('w_1062','employ','/ɪmˈplɔɪ/','verb','v. 雇佣','["em","ploy"]','["Employ workers."]','["em","ploy"]'),
('w_1063','deploy','/dɪˈplɔɪ/','verb','v. 部署','["de","ploy"]','["Deploy troops."]','["de","ploy"]'),
('w_1064','display','/dɪˈspleɪ/','verb','v. 展示','["dis","play"]','["Display products."]','["dis","play"]'),
('w_1065','portray','/pɔːˈtreɪ/','verb','v. 描绘','["port","tray"]','["Portray characters."]','["port","tray"]'),
('w_1066','contribute','/kənˈtrɪbjʊt/','verb','v. 贡献','["con","tribute"]','["Contribute to charity."]','["con","tribute"]'),
('w_1067','distribute','/dɪˈstrɪbjʊt/','verb','v. 分发','["dis","tribute"]','["Distribute flyers."]','["dis","tribute"]'),
('w_1068','attribute','/ˈætrɪbjuːt/','verb','v. 归因于','["at","tribute"]','["Attribute success to effort."]','["at","tribute"]'),
('w_1069','occupy','/ˈɒkjʊpaɪ/','verb','v. 占领','["oc","cupy"]','["Occupy the building."]','["oc","cupy"]'),
('w_1070','capacity','/kəˈpæsɪti/','noun','n. 容量','["cap"]','["Production capacity."]','["cap"]'),
('w_1071','capture','/ˈkæptʃər/','verb','v. 捕获','["cap"]','["Capture the moment."]','["cap"]'),
('w_1072','escape','/ɪˈskeɪp/','verb','v. 逃跑','["es","cap"]','["Escape from prison."]','["es","cap"]'),
('w_1073','susceptible','/səˈseptɪbl/','adj','adj. 易受影响的','["sus","cept"]','["Susceptible to disease."]','["sus","cept"]'),
('w_1074','accept','/əkˈsept/','verb','v. 接受','["ac","cept"]','["Accept the offer."]','["ac","cept"]'),
('w_1075','concept','/ˈkɒnsept/','noun','n. 概念','["con","cept"]','["Basic concepts."]','["con","cept"]'),
('w_1076','except','/ɪkˈsept/','prep','prep. 除了','["ex","cept"]','["Everyone except me."]','["ex","cept"]'),
('w_1077','receive','/rɪˈsiːv/','verb','v. 收到','["re","ceiv"]','["Receive a letter."]','["re","ceiv"]'),
('w_1078','perceive','/pəˈsiːv/','verb','v. 感知','["per","ceiv"]','["Perceive danger."]','["per","ceiv"]'),
('w_1079','deceive','/dɪˈsiːv/','verb','v. 欺骗','["de","ceiv"]','["Deceive customers."]','["de","ceiv"]'),
('w_1080','achieve','/əˈtʃiːv/','verb','v. 实现','["achiev"]','["Achieve goals."]','["achiev"]'),
('w_1081','retrieve','/rɪˈtriːv/','verb','v. 检索','["re","triev"]','["Retrieve data."]','["re","triev"]'),
('w_1082','believe','/bɪˈliːv/','verb','v. 相信','["believ"]','["I believe you."]','["believ"]'),
('w_1083','relieve','/rɪˈliːv/','verb','v. 减轻','["re","liev"]','["Relieve pain."]','["re","liev"]'),
('w_1084','review','/rɪˈvjuː/','verb','v. 复习','["re","view"]','["Review lessons."]','["re","view"]'),
('w_1085','interview','/ˈɪntəvjuː/','noun','n. 面试','["inter","view"]','["Job interview."]','["inter","view"]'),
('w_1086','visible','/ˈvɪzɪbl/','adj','adj. 可见的','["vis"]','["Visible stars."]','["vis"]'),
('w_1087','vision','/ˈvɪʒən/','noun','n. 视力','["vis"]','["Poor vision."]','["vis"]'),
('w_1088','visual','/ˈvɪʒʊəl/','adj','adj. 视觉的','["vis"]','["Visual arts."]','["vis"]'),
('w_1089','advise','/ədˈvaɪz/','verb','v. 建议','["ad","vis"]','["Advise patience."]','["ad","vis"]'),
('w_1090','devise','/dɪˈvaɪz/','verb','v. 设计','["de","vis"]','["Devise a plan."]','["de","vis"]'),
('w_1091','division','/dɪˈvɪʒən/','noun','n. 分开','["di","vis"]','["Cell division."]','["di","vis"]'),
('w_1092','provide','/prəˈvaɪd/','verb','v. 提供','["pro","vid"]','["Provide assistance."]','["pro","vid"]'),
('w_1093','evidence','/ˈevɪdəns/','noun','n. 证据','["e","vid"]','["Physical evidence."]','["e","vid"]'),
('w_1094','obvious','/ˈɒbvɪəs/','adj','adj. 显然的','["ob","vi"]','["Obvious error."]','["ob","vi"]'),
('w_1095','previous','/ˈpriːvɪəs/','adj','adj. 以前的','["pre","vi"]','["Previous day."]','["pre","vi"]'),
('w_1096','improve','/ɪmˈpruːv/','verb','v. 改进','["im","prov"]','["Improve skills."]','["im","prov"]'),
('w_1097','approve','/əˈpruːv/','verb','v. 批准','["ap","prov"]','["Approve the budget."]','["ap","prov"]'),
('w_1098','reaction','/riˈækʃən/','noun','n. 反应','["re","act"]','["Chemical reaction."]','["re","act"]'),
('w_1099','action','/ˈækʃən/','noun','n. 行动','["act"]','["Take action."]','["act"]'),
('w_1100','active','/ˈæktɪv/','adj','adj. 积极的','["act"]','["Active lifestyle."]','["act"]');
