-- 添加词汇 1201-1400
INSERT INTO words (word_id, word, phonetic, pos, definition, family, examples, roots) VALUES
('w_1201','passion','/ˈpæʃən/','noun','n. 激情','["pass"]','["Passion for music."]','["pass"]'),
('w_1202','passive','/ˈpæsɪv/','adj','adj. 被动的','["pass"]','["Passive smoking."]','["pass"]'),
('w_1203','passport','/ˈpɑːspɔːt/','noun','n. 护照','["pass","port"]','["Valid passport."]','["pass","port"]'),
('w_1204','password','/ˈpɑːswɜːd/','noun','n. 密码','["pass","word"]','["Strong password."]','["pass","word"]'),
('w_1205','surpass','/səˈpɑːs/','verb','v. 超越','["sur","pass"]','["Surpass expectations."]','["sur","pass"]'),
('w_1206','compassion','/kəmˈpæʃən/','noun','n. 同情','["com","pass"]','["Show compassion."]','["com","pass"]'),
('w_1207','broadcast','/ˈbrɔːdkɑːst/','verb','v. 广播','["broad","cast"]','["Broadcast news."]','["broad","cast"]'),
('w_1208','forecast','/ˈfɔːkɑːst/','noun','n. 预报','["fore","cast"]','["Weather forecast."]','["fore","cast"]'),
('w_1209','forecast','/ˈfɔːkɑːst/','verb','v. 预测','["fore","cast"]','["Forecast sales."]','["fore","cast"]'),
('w_1210','cast','/kɑːst/','verb','v. 投射','["cast"]','["Cast a shadow."]','["cast"]'),
('w_1211','pilot','/ˈpaɪlət/','noun','n. 飞行员','["pilot"]','["Airline pilot."]','["pilot"]'),
('w_1212','pilot','/ˈpaɪlət/','verb','v. 试点','["pilot"]','["Pilot program."]','["pilot"]'),
('w_1213','pilot','/ˈpaɪlət/','verb','v. 驾驶','["pilot"]','["Pilot plane."]','["pilot"]'),
('w_1214','imbibe','/ɪmˈbaɪb/','verb','v. 喝','["im","bib"]','["Imbibe water."]','["im","bib"]'),
('w_1215','bible','/ˈbaɪbl/','noun','n. 圣经','["bib"]','["Read the Bible."]','["bib"]'),
('w_1216','bibliography','/ˌbɪbliˈɒɡrəfi/','noun','n. 参考文献','["biblio","graph"]','["Include bibliography."]','["biblio","graph"]'),
('w_1217','bilingual','/baɪˈlɪŋɡwəl/','adj','adj. 双语的','["bi","lingu"]','["Bilingual education."]','["bi","lingu"]'),
('w_1218','linguist','/ˈlɪŋɡwɪst/','noun','n. 语言学家','["lingu"]','["Professional linguist."]','["lingu"]'),
('w_1219','language','/ˈlæŋɡwɪdʒ/','noun','n. 语言','["langu"]','["Foreign language."]','["langu"]'),
('w_1220','linger','/ˈlɪŋɡər/','verb','v. 逗留','["ling"]','["Linger after party."]','["ling"]'),
('w_1221','lonely','/ˈləʊnli/','adj','adj. 孤独的','["lon"]','["Feel lonely."]','["lon"]'),
('w_1222','alone','/əˈləʊn/','adj','adj. 单独的','["al","one"]','["Live alone."]','["al","one"]'),
('w_1223','solitude','/ˈsɒlɪtjuːd/','noun','n. 孤独','["sol"]','["Enjoy solitude."]','["sol"]'),
('w_1224','solid','/ˈsɒlɪd/','adj','adj. 固体的','["sol"]','["Solid foundation."]','["sol"]'),
('w_1225','solidarity','/ˌsɒlɪˈdærɪti/','noun','n. 团结','["sol"]','["Show solidarity."]','["sol"]'),
('w_1226','consolidate','/kənˈsɒlɪdeɪt/','verb','v. 巩固','["con","sol"]','["Consolidate power."]','["con","sol"]'),
('w_1227','isolate','/ˈaɪsəleɪt/','verb','v. 隔离','["is","lat"]','["Isolate patients."]','["is","lat"]'),
('w_1228','insulate','/ˈɪnsjʊleɪt/','verb','v. 隔离','["in","sul"]','["Insulate pipes."]','["in","sul"]'),
('w_1229','latitude','/ˈlætɪtjuːd/','noun','n. 纬度','["lat"]','["High latitude."]','["lat"]'),
('w_1230','latent','/ˈleɪtənt/','adj','adj. 潜在的','["lat"]','["Latent talent."]','["lat"]'),
('w_1231','later','/ˈleɪtər/','adv','adv. 后来','["lat"]','["See you later."]','["lat"]'),
('w_1232','relate','/rɪˈleɪt/','verb','v. 关联','["re","lat"]','["Relate to story."]','["re","lat"]'),
('w_1233','correlate','/ˈkɒrəleɪt/','verb','v. 相关','["cor","rel"]','["Correlate data."]','["cor","rel"]'),
('w_1234','translate','/trænzˈleɪt/','verb','v. 翻译','["trans","lat"]','["Translate English."]','["trans","lat"]'),
('w_1235','illation','/ɪˈleɪʃən/','noun','n. 推论','["il","lat"]','["Deduction."]','["il","lat"]'),
('w_1236','obliterate','/əˈblɪtəreɪt/','verb','v. 抹去','["ob","lit"]','["Obliterate evidence."]','["ob","lit"]'),
('w_1237','literate','/ˈlɪtərət/','adj','adj. 识字的','["liter"]','["Computer literate."]','["liter"]'),
('w_1238','illiterate','/ɪˈlɪtərət/','adj','adj. 文盲的','["il","liter"]','["Functional illiterate."]','["il","liter"]'),
('w_1239','literacy','/ˈlɪtərəsi/','noun','n. 识字','["liter"]','["Financial literacy."]','["liter"]'),
('w_1240','oblivion','/əˈblɪviən/','noun','n. 遗忘','["ob","liv"]','["Fall into oblivion."]','["ob","liv"]'),
('w_1241','livid','/ˈlɪvɪd/','adj','adj. 苍白的','["liv"]','["Livid with rage."]','["liv"]'),
('w_1242','alive','/əˈlaɪv/','adj','adj. 活着的','["al","ive"]','["Stay alive."]','["al","ive"]'),
('w_1243','living','/ˈlɪvɪŋ/','adj','adj. 活的','["liv"]','["Living standards."]','["liv"]'),
('w_1244','deliver','/dɪˈlɪvər/','verb','v. 递送','["de","liv"]','["Deliver packages."]','["de","liv"]'),
('w_1245','delivery','/dɪˈlɪvəri/','noun','n. 递送','["de","liv"]','["Home delivery."]','["de","liv"]'),
('w_1246','revive','/rɪˈvaɪv/','verb','v. 复活','["re","vive"]','["Revive economy."]','["re","vive"]'),
('w_1247','survive','/səˈvaɪv/','verb','v. 存活','["sur","vive"]','["Survive crisis."]','["sur","vive"]'),
('w_1248','vivid','/ˈvɪvɪd/','adj','adj. 生动的','["viv"]','["Vivid description."]','["viv"]'),
('w_1249','vivacity','/vɪˈvæsɪti/','noun','n. 活泼','["viv"]','["Youthful vivacity."]','["viv"]'),
('w_1250','vital','/ˈvaɪtəl/','adj','adj. 至关重要的','["vit"]','["Vital information."]','["vit"]'),
('w_1251','vitality','/vaɪˈtælɪti/','noun','n. 活力','["vit"]','["Full of vitality."]','["vit"]'),
('w_1252','vitamin','/ˈvɪtəmɪn/','noun','n. 维生素','["vit"]','["Take vitamins."]','["vit"]'),
('w_1253','devitalize','/diːˈvaɪtəlaɪz/','verb','v. 使失去活力','["de","vit"]','["Devitalize energy."]','["de","vit"]'),
('w_1254','local','/ˈləʊkəl/','adj','adj. 当地的','["loc"]','["Local news."]','["loc"]'),
('w_1255','locate','/ləʊˈkeɪt/','verb','v. 定位','["loc"]','["Locate building."]','["loc"]'),
('w_1256','location','/ləʊˈkeɪʃən/','noun','n. 位置','["loc"]','["Perfect location."]','["loc"]'),
('w_1257','allocate','/ˈæləkeɪt/','verb','v. 分配','["al","loc"]','["Allocate budget."]','["al","loc"]'),
('w_1258','collocation','/ˌkɒləˈkeɪʃən/','noun','n. 搭配','["col","loc"]','["Word collocation."]','["col","loc"]'),
('w_1259','dislocate','/ˈdɪsləkeɪt/','verb','v. 使脱臼','["dis","loc"]','["Dislocate shoulder."]','["dis","loc"]'),
('w_1260','relocate','/riːləˈkeɪt/','verb','v. 重新安置','["re","loc"]','["Relocate office."]','["re","loc"]'),
('w_1261','biology','/baɪˈɒlədʒi/','noun','n. 生物学','["bio","log"]','["Study biology."]','["bio","log"]'),
('w_1262','biography','/baɪˈɒɡrəfi/','noun','n. 传记','["bio","graph"]','["Write biography."]','["bio","graph"]'),
('w_1263','biodegradable','/ˌbaɪəʊdɪˈɡreɪdəbl/','adj','adj. 可生物降解的','["bio","de","grad"]','["Biodegradable packaging."]','["bio","de","grad"]'),
('w_1264','symbiosis','/ˌsɪmbaɪˈəʊsɪs/','noun','n. 共生','["sym","bio"]','["Mutual symbiosis."]','["sym","bio"]'),
('w_1265','antibiotic','/ˌæntibaɪˈɒtɪk/','noun','n. 抗生素','["anti","bio"]','["Take antibiotics."]','["anti","bio"]'),
('w_1266','microbe','/ˈmaɪkrəʊb/','noun','n. 微生物','["micro","b"]','["Disease microbe."]','["micro","b"]'),
('w_1267','ambition','/æmˈbɪʃən/','noun','n. 野心','["amb"]','["Political ambition."]','["amb"]'),
('w_1268','ambient','/ˈæmbiənt/','adj','adj. 周围的','["amb"]','["Ambient lighting."]','["amb"]'),
('w_1269','ambiguous','/æmˈbɪɡjʊəs/','adj','adj. 模糊的','["amb"]','["Ambiguous wording."]','["amb"]'),
('w_1270','ambivalent','/æmˈbɪvələnt/','adj','adj. 矛盾的','["amb","val"]','["Ambivalent feelings."]','["amb","val"]'),
('w_1271','amble','/ˈæmbl/','verb','v. 漫步','["amb"]','["Amble along beach."]','["amb"]'),
('w_1272','amble','/ˈæmbl/','noun','n. 漫步','["amb"]','["Take an amble."]','["amb"]'),
('w_1273','somber','/ˈsɒmbər/','adj','adj. 阴沉的','["somb"]','["Somber mood."]','["somb"]'),
('w_1274','sombre','/ˈsɒmbər/','adj','adj. 昏暗的','["somb"]','["Sombre atmosphere."]','["somb"]'),
('w_1275','thumb','/θʌm/','noun','n. 拇指','["thumb"]','["Thumb through book."]','["thumb"]'),
('w_1276','thumbscrew','/ˈθʌmskruː/','noun','n. 拇指夹','["thumb","screw"]','["Historical thumbscrew."]','["thumb","screw"]'),
('w_1277','thaw','/θɔː/','verb','v. 融化','["thaw"]','["Ice thaws."]','["thaw"]'),
('w_1278','theory','/ˈθɪəri/','noun','n. 理论','["the","ory"]','["Scientific theory."]','["the","ory"]'),
('w_1279','theoretical','/ˌθɪəˈretɪkəl/','adj','adj. 理论的','["the","ory"]','["Theoretical basis."]','["the","ory"]'),
('w_1280','theorist','/ˈθɪərɪst/','noun','n. 理论家','["the","ist"]','["Prominent theorist."]','["the","ist"]'),
('w_1281','theologian','/ˌθɪəˈləʊdʒiən/','noun','n. 神学家','["theo","log"]','["Christian theologian."]','["theo","log"]'),
('w_1282','theology','/θiˈɒlədʒi/','noun','n. 神学','["theo","log"]','["Study theology."]','["theo","log"]'),
('w_1283','theorem','/ˈθɪərəm/','noun','n. 定理','["theo","rem"]','["Mathematical theorem."]','["theo","rem"]'),
('w_1284','anthropos','/ˈænθrəpɒs/','noun','n. 人类','["anthrop"]','["Anthropology."]','["anthrop"]'),
('w_1285','anthropology','/ˌænθrəˈpɒlədʒi/','noun','n. 人类学','["anthropo","log"]','["Cultural anthropology."]','["anthropo","log"]'),
('w_1286','philanthropy','/fɪˈlænθrəpi/','noun','n. 慈善','["phil","anthrop"]','["Practice philanthropy."]','["phil","anthrop"]'),
('w_1287','misanthrope','/ˈmɪzənθrəʊp/','noun','n. 厌世者','["mis","anthrop"]','["Become a misanthrope."]','["mis","anthrop"]'),
('w_1288','philosophy','/fɪˈlɒsəfi/','noun','n. 哲学','["phil","soph"]','["Western philosophy."]','["phil","soph"]'),
('w_1289','sophist','/ˈsɒfɪst/','noun','n. 诡辩家','["soph"]','["Ancient sophist."]','["soph"]'),
('w_1290','sophisticated','/səˈfɪstɪkeɪtɪd/','adj','adj. 复杂的','["soph"]','["Sophisticated technology."]','["soph"]'),
('w_1291','sophomore','/ˈsɒfəmɔːr/','noun','n. 大二学生','["soph","more"]','["College sophomore."]','["soph","more"]'),
('w_1292','theocracy','/θiˈɒkrəsi/','noun','n. 神权政治','["theo","cracy"]','["Ancient theocracy."]','["theo","cracy"]'),
('w_1293','democracy','/dɪˈmɒkrəsi/','noun','n. 民主','["demo","cracy"]','["Western democracy."]','["demo","cracy"]'),
('w_1294','autocracy','/ɔːˈtɒkrəsi/','noun','n. 独裁','["auto","cracy"]','["Military autocracy."]','["auto","cracy"]'),
('w_1295','bureaucracy','/bjʊəˈrɒkrəsi/','noun','n. 官僚主义','["bureau","cracy"]','["Reduce bureaucracy."]','["bureau","cracy"]'),
('w_1296','aristocracy','/ˌærɪˈstɒkrəsi/','noun','n. 贵族','["arist","cracy"]','["Historical aristocracy."]','["arist","cracy"]'),
('w_1297','monarchy','/ˈmɒnəki/','noun','n. 君主制','["mon","archy"]','["Constitutional monarchy."]','["mon","archy"]'),
('w_1298','anarchy','/ˈænəki/','noun','n. 无政府状态','["an","archy"]','["Political anarchy."]','["an","archy"]'),
('w_1299','hierarchy','/ˈhaɪərɑːki/','noun','n. 等级制度','["hier","archy"]','["Corporate hierarchy."]','["hier","archy"]'),
('w_1300','patriarchy','/ˈpeɪtriɑːki/','noun','n. 男权社会','["patria","archy"]','["Break patriarchy."]','["patria","archy"]'),
('w_1301','matriarchy','/ˈmeɪtriɑːki/','noun','n. 母权社会','["matri","archy"]','["Historical matriarchy."]','["matri","archy"]'),
('w_1302','oligarchy','/ˈɒlɪɡɑːki/','noun','n. 寡头政治','["olig","archy"]','["Corporate oligarchy."]','["olig","archy"]'),
('w_1303','technocracy','/tekˈnɒkrəsi/','noun','n. 技术专家政治','["techno","cracy"]','["Modern technocracy."]','["techno","cracy"]'),
('w_1304','plutocracy','/pluːˈtɒkrəsi/','noun','n. 财阀统治','["pluto","cracy"]','["Wealthy plutocracy."]','["pluto","cracy"]'),
('w_1305','gerontocracy','/ˌdʒerənˈtɒkrəsi/','noun','n. 老人统治','["geronto","cracy"]','["Gerontocracy in politics."]','["geronto","cracy"]'),
('w_1306','pedagogy','/ˈpedəɡɒdʒi/','noun','n. 教育学','["peda","gog"]','["Modern pedagogy."]','["peda","gog"]'),
('w_1307','demagogue','/ˈdeməɡɒɡ/','noun','n. 蛊惑人心者','["demo","gogue"]','["Political demagogue."]','["demo","gogue"]'),
('w_1308','synagogue','/ˈsɪnəɡɒɡ/','noun','n. 犹太教堂','["syn","agogue"]','["Visit synagogue."]','["syn","agogue"]'),
('w_1309','catalog','/ˈkætəlɒɡ/','noun','n. 目录','["cata","log"]','["Product catalog."]','["cata","log"]'),
('w_1310','dialogue','/ˈdaɪəlɒɡ/','noun','n. 对话','["dia","log"]','["Constructive dialogue."]','["dia","log"]'),
('w_1311','prologue','/ˈprəʊlɒɡ/','noun','n. 前言','["pro","log"]','["Book prologue."]','["pro","log"]'),
('w_1312','epilogue','/ˈepɪlɒɡ/','noun','n. 尾声','["epi","log"]','["Novel epilogue."]','["epi","log"]'),
('w_1313','monologue','/ˈmɒnəlɒɡ/','noun','n. 独白','["mono","log"]','["Dramatic monologue."]','["mono","log"]'),
('w_1314','apologize','/əˈpɒlədʒaɪz/','verb','v. 道歉','["apo","log"]','["Apologize sincerely."]','["apo","log"]'),
('w_1315','analogy','/əˈnælədʒi/','noun','n. 类比','["ana","log"]','["Draw an analogy."]','["ana","log"]'),
('w_1316','psychology','/saɪˈkɒlədʒi/','noun','n. 心理学','["psycho","log"]','["Study psychology."]','["psycho","log"]'),
('w_1317','sociology','/ˌsəʊsiˈɒlədʒi/','noun','n. 社会学','["socio","log"]','["Modern sociology."]','["socio","log"]'),
('w_1318','archaeology','/ˌɑːkiˈɒlədʒi/','noun','n. 考古学','["archaeo","log"]','["Field of archaeology."]','["archaeo","log"]'),
('w_1319','ideology','/ˌaɪdiˈɒlədʒi/','noun','n. 意识形态','["ideo","log"]','["Political ideology."]','["ideo","log"]'),
('w_1320','terminology','/ˌtɜːmɪˈnɒlədʒi/','noun','n. 术语','["termin","log"]','["Technical terminology."]','["termin","log"]'),
('w_1321','methodology','/ˌmeθəˈdɒlədʒi/','noun','n. 方法论','["method","log"]','["Research methodology."]','["method","log"]'),
('w_1322','anthropology','/ˌænθrəˈpɒlədʒi/','noun','n. 人类学','["anthropo","log"]','["Cultural anthropology."]','["anthropo","log"]'),
('w_1323','archaeology','/ˌɑːkiˈɒlədʒi/','noun','n. 考古学','["archaeo","log"]','["Classical archaeology."]','["archaeo","log"]'),
('w_1324','genealogy','/ˌdʒiːniˈælədʒi/','noun','n. 家谱','["genea","log"]','["Trace genealogy."]','["genea","log"]'),
('w_1325','epidemiology','/ˌepɪˌdiːmiˈɒlədʒi/','noun','n. 流行病学','["epidemio","log"]','["Study epidemiology."]','["epidemio","log"]'),
('w_1326','rheumatology','/ˌruːməˈtɒlədʒi/','noun','n. 风湿病学','["rheumato","log"]','["Rheumatology department."]','["rheumato","log"]'),
('w_1327','dermatology','/ˌdɜːməˈtɒlədʒi/','noun','n. 皮肤学','["dermato","log"]','["Visit dermatology."]','["dermato","log"]'),
('w_1328','neurology','/njʊəˈrɒlədʒi/','noun','n. 神经学','["neuro","log"]','["Neuroscience."]','["neuro","log"]'),
('w_1329','biology','/baɪˈɒlədʒi/','noun','n. 生物学','["bio","log"]','["Marine biology."]','["bio","log"]'),
('w_1330','ecology','/iːˈkɒlədʒi/','noun','n. 生态学','["eco","log"]','["Environmental ecology."]','["eco","log"]'),
('w_1331','zoology','/zəʊˈɒlədʒi/','noun','n. 动物学','["zoo","log"]','["Study zoology."]','["zoo","log"]'),
('w_1332','physiology','/ˌfɪziˈɒlədʒi/','noun','n. 生理学','["physio","log"]','["Human physiology."]','["physio","log"]'),
('w_1333','pathology','/pəˈθɒlədʒi/','noun','n. 病理学','["patho","log"]','["Medical pathology."]','["patho","log"]'),
('w_1334','geology','/dʒiˈɒlədʒi/','noun','n. 地质学','["geo","log"]','["Study geology."]','["geo","log"]'),
('w_1335','psychology','/saɪˈkɒlədʒi/','noun','n. 心理学','["psycho","log"]','["Child psychology."]','["psycho","log"]'),
('w_1336','sociology','/ˌsəʊsiˈɒlədʒi/','noun','n. 社会学','["socio","log"]','["Urban sociology."]','["socio","log"]'),
('w_1337','anthropology','/ˌænθrəˈpɒlədʒi/','noun','n. 人类学','["anthropo","log"]','["Cultural anthropology."]','["anthropo","log"]'),
('w_1338','archaeology','/ˌɑːkiˈɒlədʒi/','noun','n. 考古学','["archaeo","log"]','["Field archaeology."]','["archaeo","log"]'),
('w_1339','methodology','/ˌmeθəˈdɒlədʒi/','noun','n. 方法论','["method","log"]','["Scientific methodology."]','["method","log"]'),
('w_1340','terminology','/ˌtɜːmɪˈnɒlədʒi/','noun','n. 术语学','["termin","log"]','["Medical terminology."]','["termin","log"]'),
('w_1341','ideology','/ˌaɪdiˈɒlədʒi/','noun','n. 思想体系','["ideo","log"]','["Political ideology."]','["ideo","log"]'),
('w_1342','analogy','/əˈnælədʒi/','noun','n. 类比','["ana","log"]','["By analogy."]','["ana","log"]'),
('w_1343','dialogue','/ˈdaɪəlɒɡ/','noun','n. 对话','["dia","log"]','["Meaningful dialogue."]','["dia","log"]'),
('w_1344','monologue','/ˈmɒnəlɒɡ/','noun','n. 独白','["mono","log"]','["Dramatic monologue."]','["mono","log"]'),
('w_1345','prologue','/ˈprəʊlɒɡ/','noun','n. 序幕','["pro","log"]','["Story prologue."]','["pro","log"]'),
('w_1346','epilogue','/ˈepɪlɒɡ/','noun','n. 尾声','["epi","log"]','["Movie epilogue."]','["epi","log"]'),
('w_1347','catalog','/ˈkætəlɒɡ/','noun','n. 目录册','["cata","log"]','["Library catalog."]','["cata","log"]'),
('w_1348','chronology','/krəˈnɒlədʒi/','noun','n. 年表','["chrono","log"]','["Historical chronology."]','["chrono","log"]'),
('w_1349','etymology','/ˌetɪˈmɒlədʒi/','noun','n. 词源学','["etymo","log"]','["Word etymology."]','["etymo","log"]'),
('w_1350','tautology','/tɔːˈtɒlədʒi/','noun','n. 同义反复','["tauto","log"]','["Logical tautology."]','["tauto","log"]'),
('w_1351','astrology','/əˈstrɒlədʒi/','noun','n. 占星术','["astro","log"]','["Practice astrology."]','["astro","log"]'),
('w_1352','mineralogy','/ˌmɪnəˈrælədʒi/','noun','n. 矿物学','["minera","log"]','["Study mineralogy."]','["minera","log"]'),
('w_1353','physiology','/ˌfɪziˈɒlədʒi/','noun','n. 生理学','["physio","log"]','["Plant physiology."]','["physio","log"]'),
('w_1354','morphology','/mɔːˈfɒlədʒi/','noun','n. 形态学','["morpho","log"]','["Cell morphology."]','["morpho","log"]'),
('w_1355','toxicology','/ˌtɒksɪˈkɒlədʒi/','noun','n. 毒理学','["toxico","log"]','["Forensic toxicology."]','["toxico","log"]'),
('w_1356','virology','/vaɪəˈrɒlədʒi/','noun','n. 病毒学','["viro","log"]','["Medical virology."]','["viro","log"]'),
('w_1357','bacteriology','/bækˌtɪəriˈɒlədʒi/','noun','n. 细菌学','["bacterio","log"]','["Industrial bacteriology."]','["bacterio","log"]'),
('w_1358','entomology','/ˌentəˈmɒlədʒi/','noun','n. 昆虫学','["entomo","log"]','["Study entomology."]','["entomo","log"]'),
('w_1359','ornithology','/ˌɔːnɪˈθɒlədʒi/','noun','n. 鸟类学','["ornitho","log"]','["Field ornithology."]','["ornitho","log"]'),
('w_1360','herpetology','/ˌhɜːpɪˈtɒlədʒi/','noun','n. 爬行动物学','["herpeto","log"]','["Herpetology research."]','["herpeto","log"]'),
('w_1361','ichthyology','/ˌɪkθiˈɒlədʒi/','noun','n. 鱼类学','["ichthyo","log"]','["Marine ichthyology."]','["ichthyo","log"]'),
('w_1362','malacology','/ˌmæləˈkɒlədʒi/','noun','n. 软体动物学','["malaco","log"]','["Malacology studies mollusks."]','["malaco","log"]'),
('w_1363','conchology','/kɒŋˈkɒlədʒi/','noun','n. 贝壳学','["concho","log"]','["Shell collection."]','["concho","log"]'),
('w_1364','phylogeny','/faɪˈlɒdʒəni/','noun','n. 系统发育','["phylo","gen"]','["Phylogeny of species."]','["phylo","gen"]'),
('w_1365','ontogeny','/ɒnˈtɒdʒəni/','noun','n. 个体发育','["onto","gen"]','["Human ontogeny."]','["onto","gen"]'),
('w_1366','cytology','/saɪˈtɒlədʒi/','noun','n. 细胞学','["cyto","log"]','["Cell biology."]','["cyto","log"]'),
('w_1367','histology','/hɪˈstɒlədʒi/','noun','n. 组织学
